### ISSUE TITLE
20220215気になったこと

### ISSUE THREAD

**Issue by AichiStakePool** [btbf/spojapanguild#1]
■該当ページURL
http://49.12.225.142:8000/

■修正前
（１）サーバー代について
サーバー代(最小構成２台)/月	8000円～16000円
の部分…日本のSPOはまず日本のサーバーを使用すると思うので、日本のサーバー代は海外に比べて高めですので、メモリ16GBならば8000円～16000円/1台かなと思いました。

（２）オペレーター報酬について
プール総報酬ー（①＋②）＝オペレーター報酬

■修正後
（１）最低２台必要で、２台で月16000円～32000円
（２）プール総報酬ー（①＋②）＝委任者報酬

**Comment by satoshi-tokyo** [comment]
プール総報酬ー（①＋②）＝委任者報酬

について、下記になるのかなあと気になったため書き込みさせていただきます。
（表現したいことは間違いないので、もし意図と違っていたら気になさらないでくださいませ）

![image](https://user-images.githubusercontent.com/40759599/154074048-9c3676f2-28ee-4d31-807d-81cb0d0a6480.png)

**Comment by sakakibaraakio** [comment]
現在の記述に合わせて厳密に言うと、
①＋（プール総報酬-①）*②＝委任者報酬

となると思いますが、最初の説明ページなので可能な限りわかりやすい説明にしたいですね。

候補をいくつか出すと、

１、

> オペレーター報酬
> 
> プール総報酬＝１エポックで生成したブロック数によって決定（1ブロック単位で貰える報酬量はほんの少しずつ減少していきます）
> ①固定報酬　 最低340ADAから設定可能
> ②変動報酬　0%～100%まで設定可能な変動手数料を、プール総報酬から固定報酬を引いた残りに掛けたもの
> 
> オペレータ報酬＝①+②


２、

> オペレーター報酬
> 
> 各SPOが自由に設定可能な固定手数料、変動手数料が影響します。
> 固定手数料：340ADA～
> 変動手数料：０%～１００％
> 
> ブロックを生成した数によって、2エポック後にプール全体へ報酬が与えられます。
> その全体報酬からまず固定手数料がオペレータ報酬として引かれ、さらに残りの報酬に変動手数料を掛けたものもオペレータ報酬となります。
> 残りの報酬は委任量に応じて委任者へ分配されます。


ご意見や更なる提案を宜しくお願いします。

**Comment by btbf** [comment]
> プール総報酬＝１エポックで生成したブロック数によって決定（1ブロック単位で貰える報酬量はほんの少しずつ減少していきます）
この書き方だと単純に1ブロックあたりいくらぐらいですか？みたいな質問が出ると思うので、避けたいです。

委任量が10Kのプールで1ブロック生成した場合と、１Mのプールで1ブロック生成した場合では総報酬量は全然違うので
「委任量と割り当てスケジュールLuck指数にもとづいたブロック生成数によって変動」のほうがいいと思いますがいかがでしょうか？

**Comment by sakakibaraakio** [comment]
> この書き方だと単純に1ブロックあたりいくらぐらいですか？みたいな質問が出ると思うので、避けたいです
なるほどその通りですね。
正しい情報を伝えつつも、なるべく複雑さを出さずに説明するのが必要でそのためにはプール総報酬の説明が難点だな、
とは思っていたのですが、この説明だとちょっと甘いですね。
そこをもっと考慮してもうちょっと考えてみます。


>委任量が10Kのプールで1ブロック生成した場合と、１Mのプールで1ブロック生成した場合では総報酬量は全然違う
こちらですが、総報酬量は同じな気がします。
委任量に対する報酬量を表す報酬率は大きく変わってきますが、1ブロック生成することでプール全体に与えられる報酬量は
650ADA～700ADAで、委任量に関わらない数字になるという認識です。

**Comment by AichiStakePool** [comment]
> 委任量が10Kのプールで1ブロック生成した場合と、１Mのプールで1ブロック生成した場合では総報酬量は全然違う

報酬はブロック生成数だけでなく、委任量にも依存するのでしょうか？ソースがあれば見たいです。
委任量が多いほどブロック生成数の期待値が多いというのは知っています。
ですが、どちらも１ブロックの生成であれば総報酬は同じだという認識でした。

私はシンプルの方が好きですね。
例えば、JapaneseSPOさんの記事（Sugarさんとか）で報酬についての詳しい記事があるので、
例えば詳細はリンクを貼るなどしておいて、ここではとりあえず
①＋②＝オペレーター報酬
で良いのではないかと思いました。

**Comment by sakakibaraakio** [comment]
Aichiさんありがとうございます！
報酬が減っていくという情報はやはり扱いが難しいですね。
マニュアルの説明では具体的な数字は書かない方が良さそうです。

**Comment by btbf** [comment]
@AichiStakePool @sakakibaraakio 
認識してる定義がズレてますか？
MIYABIさんのブログで詳しく解説されてます
https://miyabi-kyoto.org/cardano_staking_reward_calculation/#toc8

**Comment by btbf** [comment]
認識の勘違いでした。
ステーク量でブロック生成期待値が変動します。

ですが、このマニュアルでは1ブロック平均いくらという表現は避けたいです。

**Comment by AichiStakePool** [comment]
> ①＋（ プール総報酬 - ① ）* ②＝オペレーター報酬

表現としてはこうなりますね。
sakakibaraさん、ありがとうございます！

**Comment by btbf** [comment]
Fixed
