### ISSUE TITLE
誤字「1-11.SSHの2段階認証を設定する ２つの目ウィンドウ」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#10]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-11ssh2

■項番(あれば)
1-11.SSHの2段階認証を設定する
注意

■修正前
２つの目ウィンドウ

■修正後
二つ目のウィンドウ

**Comment by btbf** [comment]
Fixed.
Thank you!
