### ISSUE TITLE
追加　運用マニュアル　プール廃止　「エアギャップで作成したstake-dereg.certをBPへ移動」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#108]
■該当ページURL
https://docs.spojapanguild.net/operation/pool-retire/#4

■項番(あれば)
プール廃止 　4.ステークキー解除手順

■修正前
ステークキー登録解除証明書作成
エアギャップオフラインマシン

cardano-cli stake-address deregistration-certificate \
    --stake-verification-key-file stake.vkey \
    --out-file stake-dereg.cert

ステークキー登録料算出
ブロックプロデューサノード

keyDeposit=$(cat $NODE_HOME/params.json | jq -r '.stakeAddressDeposit')
echo keyDeposit: $keyDeposit

■修正後
ステークキー登録解除証明書作成
エアギャップオフラインマシン

cardano-cli stake-address deregistration-certificate \
    --stake-verification-key-file stake.vkey \
    --out-file stake-dereg.cert
    

ファイル転送

エアギャップのstake-dereg.cert を ブロックプロデューサノードのcnodeディレクトリにコピーします。
graph LR A[エアギャップ] -->|stake-dereg.cert| B[BP];
    

ステークキー登録料算出
ブロックプロデューサノード

keyDeposit=$(cat $NODE_HOME/params.json | jq -r '.stakeAddressDeposit')
echo keyDeposit: $keyDeposit

**Comment by btbf** [comment]
Fixed
