### ISSUE TITLE
修正「1-11.SSHの2段階認証を設定する 先頭の @include common-auth〜」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#11]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-11ssh2

■項番(あれば)

■修正前
先頭の @include common-authを#を付与してコメントアウトする

■修正後
@include common-authの先頭へ#を付与する。

**Comment by sakakibaraakio** [comment]
「4行目の@include common-authの先頭へ#を付与してコメントアウトする。」

だとさらにわかりやすくなるかもしれませんね。

**Comment by btbf** [comment]
Fixed.
Thank you!
