### ISSUE TITLE
修正　構築マニュアル2-7 「gliveのパス通しを修正プログラム仕様に」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#119]
■該当ページURL
https://docs.spojapanguild.net/setup/2-node-setup/#2-7-gliveview

■項番(あれば)
2-7. gLiveViewのインストール 

■修正前
ヒント

スクリプトへのパスを通し、任意の単語で起動出来るようにする。

echo alias glive="$NODE_HOME/scripts/gLiveView.sh" >> $HOME/.bashrc
source $HOME/.bashrc

■修正後
ヒント

スクリプトへのパスを通し、任意の単語で起動出来るようにする。

echo alias glive="'cd $NODE_HOME/scripts; ./gLiveView.sh'" >> $HOME/.bashrc
source $HOME/.bashrc

**Comment by btbf** [comment]
Fixed
