### ISSUE TITLE
修正「1-11.SSHの2段階認証を設定する スクラッチコードがひょうじ〜」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#12]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-11ssh2

■項番(あれば)

■修正前
その下には緊急時のスクラッチコードがひょうじされますので、忘れずに書き留めておいて下さい。

■修正後
その下には緊急時のスクラッチコードが表示されますので、忘れずに書き留めておいて下さい。

**Comment by btbf** [comment]
Fixed.
Thank you!
