### ISSUE TITLE
修正　構築マニュアル0 「マニュアルの対応バージョン記述およびドキュメント更新情報のリンク先」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#13]
■該当ページURL
http://49.12.225.142:8000/setup/0-start-guide/

ページ最初の
「情報」
項目にて、
「このマニュアルは、カルダノノードv1.32.1に対応しています。」
とありますが、最新バージョンのv1.33.0の構築に対応しているように見えます。
また、同項目の
[ドキュメント更新情報はこちら](http://49.12.225.142:8000/setup/0-start-guide/README.md)
のリンク先が404となっているようです。

**Comment by btbf** [comment]
Fixed.
Thank you!
