### ISSUE TITLE
修正　構築マニュアル1-3　「id_rsaをダウンロードする　改行抜け」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#14]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-3ssh

■項番(あれば)
１－３
id_rsaをダウンロードする

■修正前
1.R-loginの場合はファイル転送ウィンドウを開く
2.左側ウィンドウ(ローカル側)は任意の階層にフォルダを作成する。
3.右側ウィンドウ(サーバ側)は「.ssh」フォルダを選択する
4.右側ウィンドウから、id_rsaファイルの上で右クリックして「ファイルのダウンロード」を選択する
5.一旦サーバからログアウトする 6.R-Loginのサーバ接続編集画面を開き、「SSH認証鍵」をクリックし4でダウンロードしたファイルを選ぶ 7.サーバへ接続する

■修正後
1.R-loginの場合はファイル転送ウィンドウを開く
2.左側ウィンドウ(ローカル側)は任意の階層にフォルダを作成する。
3.右側ウィンドウ(サーバ側)は「.ssh」フォルダを選択する
4.右側ウィンドウから、id_rsaファイルの上で右クリックして「ファイルのダウンロード」を選択する
5.一旦サーバからログアウトする 
6.R-Loginのサーバ接続編集画面を開き、「SSH認証鍵」をクリックし4でダウンロードしたファイルを選ぶ 
7.サーバへ接続する

**Comment by btbf** [comment]
Fixed.
Thank you!
