### ISSUE TITLE
[バグ] (sjgtool.sh) psの結果に複数のcardano-nodeがある場合、ツールが起動しない

### ISSUE THREAD

**Issue by nori-crypto** [btbf/spojapanguild#140]
### バグについて
psの結果に複数の`cardano-node`がある場合、「ノードを起動して再度実行してください」になります。

### 再現方法
1. ノードを起動状態にする。
2. パスなどに`cardano-node`を含むプロセスが複数実行された状態にする。
3. `./sjgtool.sh`を起動する。

### 期待される動作
ツールが通常起動する。

### 追加の状況
`ps -ef | grep cardano-node | grep -v grep | wc -l`が2以上となるため、`${node_check} == "1"`を通過できていないようです。

**Comment by btbf** [comment]
参考までに、複数ノード起動はどのような使い方でしょうか？
またBPorリレーどちらでしょうか？

**Comment by nori-crypto** [comment]
BPです。ノードは1つのみ起動しています。
監視などのために自作のスクリプトがいくつか動いているのですが、
そのパスや渡しているオプションに`cardano-node`の語句が含まれておりgrepに引っかかってしまいます。

**Comment by btbf** [comment]
なるほど！ありがとうございます。

**Comment by btbf** [comment]
cardano-nodeのプロセスID有無で判定する方式へ変更。
