### ISSUE TITLE
修正 運用マニュアル SJG TOOL 「TraceMempoolがtrueでも”条件付きOK”」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#143]
TraceMempoolがtrueでTx流入が確認できている状態でも、”条件付きOK”の表示になるようです。
![スクリーンショット 2022-04-10 165656](https://user-images.githubusercontent.com/69729884/162608518-c358cfd2-820c-4ec4-bc06-43213c736f0a.png)

**Comment by btbf** [comment]
Fixed
