### ISSUE TITLE
[バグ]

### ISSUE THREAD

**Issue by AichiStakePool** [btbf/spojapanguild#146]
**バグについて説明してください。
報酬引き出し時、stake.addrのファイル名がstake.addr以外だと以下の画像のようになる。
<img width="485" alt="bug01" src="https://user-images.githubusercontent.com/99731543/162615998-4f5eb53f-c4a8-444b-84e3-d124b2bef9bd.png">
**再現方法**について
GuildToolにてstake.addrのファイル名がstake.addr以外で
[1] ウォレット操作 → [3] 報酬/資金出金 → プール報酬出金[1] 任意のアドレスへ出金
と選択。

**期待される動作**
エラーが起きない

**追加の状況**について
（要望）
上記画像では
出金先のアドレスを入力してください： > 
の戻り値としてCtrl+Cで強制終了しています。
送金をキャンセルする場合、Ctrl+Cを押すとキャンセルできることをどこかに記載しておくとよいかもしれません。

**Comment by btbf** [comment]
ファイル名がstake.addr以外にも対応しました。

出金先入力の画面で送金をキャンセルできるよう、以下の文言と処理を追加しました。
```
出金をキャンセルする場合は 1 を入力してEnterを押してください
```
