### ISSUE TITLE
提案：「payment.addrへ出金」の表示について

### ISSUE THREAD

**Issue by Amayori007** [btbf/spojapanguild#148]
**問題点**
[１]ウォレット操作 ⇒ [３]報酬/資金出金 ⇒ [２]payment.addrへ出金
上記の操作を行うと、即処理が始まってしまうため、経験が浅い運用者に誤解を与えてしまう恐れがある。

**解決策・提案**
フールプルーフの観点から、処理の前に確認画面を挟むか、キャンセルする際に必要な操作(Ctrt+C等)を表記しておくと分かり易いと思います。

【例】
・[運用者のpayment.addrを表示]に送金します。処理を継続しますか？(Yes/No)
・処理を中断する場合は「Ctrtキー」+「Cキー」を入力してください。

**追加情報**
現在の表示でも問題ないとは思うのですが、運用者の技量によってはどんな操作をされるか分からないので、念のための提案です。
検討の程、よろしくお願いいたします。

**Comment by btbf** [comment]
Enterを押すことでTx送信かキャンセルを選択できるため、以下のように文言を追加しました。

```
■Txファイルを作成しました。エアギャップオフラインマシンで以下の操作を実施してください

<中略>

1～3の操作が終わったらEnterを押してください
出金をキャンセルする場合はEnterを押して2を入力してください
```
