### ISSUE TITLE
修正　構築マニュアル1-9　「リレーノードのIPのみ受け付ける用に設定」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#15]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-8fail2ban

■項番(あれば)
１－９　ファイアウォールを構成する

■修正前
Prometheus-node-exporter用のポート12798・9100をリレーノードのIPのみ受け付ける用に設定してください。 

ブロックプロデューサーノードでは、リレーノードのIPのみ受け付ける用に設定してください。 

■修正後
Prometheus-node-exporter用のポート12798・9100をリレーノードのIPのみ受け付けるように設定してください。 

ブロックプロデューサーノードでは、リレーノードのIPのみ受け付けるように設定してください。

**Comment by btbf** [comment]
Fixed
Thank you!
