### ISSUE TITLE
修正 SPO JAPAN GUILD TOOLv1.2-Beta 「TraceMempool:false　の際の”Tx流入数”のメッセージ」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#155]
TraceMempool:true　の際の問題は解決され、OK表示になりました。
![スクリーンショット 2022-04-11 071756](https://user-images.githubusercontent.com/69729884/162643013-6f5e0744-b26d-4b2d-aba0-7f29d39dab59.png)

しかし今度は、TraceMempool:false　の際にNG表示が出るようになりました。

加えて、エラーメッセージ内でmainnet-topology.jsonと表記されるべき部分が、api-topology.jsonになっているようです。
![スクリーンショット 2022-04-11 075540](https://user-images.githubusercontent.com/69729884/162643431-b34143f3-bb15-4130-8f26-84575b1ef031.png)

**Comment by akyo3** [comment]
重複してしまうので榊原さんのissueに追記します
表現変更依頼

◆修正前
・当サーバーのFW

◆修正後
・当サーバーのファイアウォール

■
リレーで使用することを想定していないのであれば
「当サーバー」→「BP」としておいた方が質問回数は減ると思います
