### ISSUE TITLE
提案　構築マニュアル　2-2 　「nodeとcliビルド後のバージョン確認について」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#17]
■該当ページURL
http://49.12.225.142:8000/setup/2-node-setup/#2-1-cabalghc

■項番(あれば)
2-2. ソースコードからビルド

■問題点
cardano-nodeとcardano-cliのビルド後のバージョン確認作業で、

「cardano-cli と cardano-nodeのバージョンが上記で指定したGitタグバージョンであることを確認してください。」

とありますが、最新のコマンドではバージョンは指定せずcurlとjqによる自動取得になっているので、
「上記で指定したGitタグバージョン」が何のことかわかり辛いかもしれません。
（git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .tag_name)
の戻りもcardano-nodeとcliのビルドの際に流されていると思われます。）

■修正案

cardano-cli と cardano-nodeのバージョンが最新であることを確認します。
```
cardano-node version
cardano-cli version
```
最新バージョン確認コマンド
```
curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .tag_name
```

**Comment by btbf** [comment]
Fixed.
Thank you!
