### ISSUE TITLE
文言追加　構築マニュアル2-7 　「gLiveViewのBP/リレー自動判別は4-5終了後」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#18]
■該当ページURL
http://49.12.225.142:8000/setup/2-node-setup/#2-6-systemd

■項番(あれば)
2-7. gLiveViewのインストール

■修正前

gLiveViewについて▼

このツールを立ち上げてもノードは起動しません。ノードは別途起動しておく必要があります
リレー／BPは自動判別されます。
リレーノードでは基本情報に加え、トポロジー接続状況を確認できます。
BPノードでは基本情報に加え、KES有効期限、ブロック生成状況を確認できます。

■修正後

gLiveViewについて▼

このツールを立ち上げてもノードは起動しません。ノードは別途起動しておく必要があります
リレー／BPの自動判別は、手順4-5終了後に行われるようになります。
リレーノードでは基本情報に加え、トポロジー接続状況を確認できます。
BPノードでは基本情報に加え、KES有効期限、ブロック生成状況を確認できます。

**Comment by btbf** [comment]
Fixed.
Thank you!
