### ISSUE TITLE
文言追加：SSH鍵認証方式へ切り替え（~/.sshフォルダがない場合等）

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#181]
■該当ページURL
https://docs.spojapanguild.net/setup/1-ubuntu-setup/

■項番(あれば)
1-3.SSH鍵認証方式へ切り替え
　ペア鍵の作成

■修正前
ペア鍵の作成
ssh-keygen -t rsa

■修正後
ls ~/.ssh

戻り値が、"No such file or directory"だった場合、サーバーによってない場合もあるのでなければ作成してください
mkdir ~/.ssh

ある場合
cd ~/.ssh
ssh-keygen -t rsa
ls

id_rsa（秘密鍵）とid_rsa.pub（公開鍵）というファイルが作成されているか確認する。 ~~

◆サーバーによってsshフォルダがない場合もあるため追加依頼。
それと$HOMEでペア鍵の作成するとsshフォルダに生成されなかったのでsshフォルダへ移動してペア鍵の作成することとなるかと思います。（VPS会社？サーバー？によるのかなと）

補足：比較的どのVPSでもsshフォルダはありそうですが、なかったためその場合も書いてあると良いかな？と思ったのでIssueにあげてます。

**Comment by btbf** [comment]
sshフォルダがない場合、ssh-keygen -t rsaで自動的に作成されるはずですがどうでしょうか？
![image](https://user-images.githubusercontent.com/37224549/167426052-993bd00c-1c30-4b7d-b85e-86401fd29905.png)

**Comment by akyo3** [comment]
たいていのサーバーではそのようになると思います。VPS会社によりけりかと思いますが、今回の私のケースではその後.sshディレクトリ移動できず、＄HOMEにキーが作成されている状況でした。
今のところそのような報告があがっていない場合特にDoc修正しなくてもよいかもしれません。
