### ISSUE TITLE
修正　構築マニュアル2-8　「エアギャップマシンにおける$NODE_HOMEの作成およびオフライン化」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#19]
■該当ページURL
http://49.12.225.142:8000/setup/2-node-setup/#2-7-gliveview

■項番(あれば)
2-8. エアギャップオフラインマシンの作成

「目次1～2までをエアギャップオフラインマシンで実行する」
となっていますが、1~2だけだとエアギャップマシンにて$NODE_HOMEが作成されていないようです。
また、作業終了後にオフライン環境にすることも追記していたほうが良いかもしれません。

■修正前
目次1～2までをエアギャップオフラインマシンで実行する

■修正後
2-1. Cabal/GHCインストール  と　2-2. ソースコードからビルド 　をエアギャップオフラインマシンで実行します。

$NODE_HOMEを作成します。
```
mkdir $NODE_HOME
```

終了後、エアギャップオフラインマシンをオフライン環境にします。
例）VirtualBoxで構築している場合、
設定→ネットワーク→”ネットワークアダプターを有効化”のチェックを外す

**Comment by btbf** [comment]
Fixed
Thank you!
