### ISSUE TITLE
文言追加： Kes更新（gtool）のファイルハッシュ値の確認について

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#190]
2. ファイルハッシュ値確認
BPで実行しているので仕方ないと思いますが、このままではエアギャップで出力したファイルハッシュ値とBPで出力したファイルハッシュ値が等しいかの確認ができないと思います。（ツール実行中のため）

特に新規SPOはおそらく分からないと思います。

そのため補足としてターミナルソフトを複製して確認する。
などの文言を追加してほしいです。
またツール実行後でも問題ないのであればツール実行後に確認するなど。

![unnamed (1)](https://user-images.githubusercontent.com/80967103/167840585-0101c97e-f8e4-48f6-ad80-0b23e9cbc9d0.png)

**Comment by btbf** [comment]
BPでは新しいファイルのハッシュ値が表示されているので、そこと比較するような文言になってます。
![image](https://user-images.githubusercontent.com/37224549/173178916-6003e51a-e520-4049-9e6e-36b874ba2c15.png)

**Comment by akyo3** [comment]
■新しいkesファイルの作成…で表示されている
ハッシュ値の箇所を見落としていた？かもしれません
これであれば比較できると思います、ありがとうございます！
