### ISSUE TITLE
誤字「SPOとは？ Oparator」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#2]
■該当ページURL
http://49.12.225.142:8000/#spo_1

■項番(あれば)
SPOとは？

■修正前
SPO＝Stake Pool Oparator

■修正後
SPO＝Stake Pool Operator

◆Opa~ではなく、Ope

<img width="205" alt="スクリーンショット 2022-02-15 21 18 12" src="https://user-images.githubusercontent.com/80967103/154060686-3471044e-2382-4001-a093-7603bea6d1fd.png">
~

**Comment by btbf** [comment]
Fixed.
Thank you!
