### ISSUE TITLE
修正　構築マニュアル4-2　不要文字削除依頼　「$HOME/cold-keys.」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#20]
■該当ページURL
http://49.12.225.142:8000/setup/4-bp-setup/#1kes

■項番(あれば)
4-2.コールドキーの作成

■修正前
コールドキーは次のパスに格納されます $HOME/cold-keys.

■修正後
コールドキーは次のパスに格納されます $HOME/cold-keys

**Comment by btbf** [comment]
Fixed
Thank you!
