### ISSUE TITLE
Grafanaダッシュボード改善およびSJGWebサイトへ掲載希望

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#203]
**問題点
現状のダッシュボードでは、運用における監視項目が少ないと思われるため、次の監視項目の拡充希望(増える可能性あり)

**解決策・提案**。
提案：Swap領域や、Disk使用率などのパネル追加やChain Density等の閾値設定を追加希望。

実装してほしいページや機能：SJGWebサイトにGrafana関連項目のページを作成してほしい。

そこへみなさんの案の各ダッシュボードが展開される。
例えばAさんのダッシュボード、Bさんのダッシュボードなど
(最終的には運用における監視項目やアラートが拡充されることや視認性が高く監視しやすいことを目標としたい)

**追加情報**
機能リクエストに関するその他のドキュメントやスクリーンショットをここに追加してください。
◆まずは赤枠からと考えております。
「Swap領域や、Disk使用率などのパネル追加やChain Density等の閾値設定」

<img width="1672" alt="スクリーンショット 2022-07-03 0 50 03" src="https://user-images.githubusercontent.com/80967103/177007702-0eb2402b-5bd9-4e05-9867-7ab0d550cc6d.png">

<img width="1672" alt="スクリーンショット 2022-07-03 0 53 52" src="https://user-images.githubusercontent.com/80967103/177007629-8f588dbf-3b41-48ab-9b20-47464b6cf913.png">

アラート設定にはこちらを使用してください。指摘がある場合は修正します。
https://github.com/akyo3/etc/blob/main/Grafana%20Alert%20setting.md

**Comment by sakakibaraakio** [comment]
現在マニュアルで使用されているGrafanaダッシュボードを一部変更してみました。
https://github.com/sakakibaraakio/etc/blob/main/grafana%20dashboard%20JSG

 

> 変更点
> ・Mempool bytes、Mempool transactions、TXs processedの3つのパネルを削除
> →マニュアルのGrafana導入時には既にMempoolTraceがfalseになっていて、trueにした際の確認はgtoolで出来る為
> 
> ・Chain density % において、4.5以下の範囲で色が変化するように
> →普段は表示されませんが 4.5を下回る期間が出てくると赤い範囲が見えてきます。
> Graph(old)を使用してますが、閾値で色が変わる系の設定はstatを使った方が見た目が良いかもしれません。とりあえず今回はこちらで
> 
> ・メモリ使用量関連の単位を、bytes(SI)からbytes(IEC)に変更
> 
> ・新しくパネルを追加

> > Disk usage rate
> > →ディスク使用率、10%以下で赤文字に
> > 
> > Missed slot
> > →ミススロット
> > 
> > Swap Memory usage
> > →スワップメモリ使用量
> 

![aaa](https://user-images.githubusercontent.com/69729884/177019953-027fd7c5-f8fc-4633-8d0f-cd0cbf66328d.png)

**Comment by akyo3** [comment]
現在のSJG DocsにあるGrafanaDashboardのjsonを改良しました。Metricsは榊原さんとほぼほぼ同じだったので一部参考にして適用。
・提案で出したSwap領域や、Disk使用率などのパネル追加やChain Density等の閾値設定を追加。
・加えて遊び心としてSJGのWebサイト、Docs、アライアンスリスト（Cexplorer.io）のパネル追加。

まずは案出しなので改良点があれば教えてください。

<img width="1672" alt="スクリーンショット 2022-07-06 23 24 17" src="https://user-images.githubusercontent.com/80967103/177573436-30daa075-c644-4763-a210-f505b22ec84e.png">

<img width="1672" alt="スクリーンショット 2022-07-06 23 24 38" src="https://user-images.githubusercontent.com/80967103/177573480-39ef47b1-2de6-4d92-a5bc-c82da6e9a223.png">

https://github.com/akyo3/Extends-SJG-Knowledge/blob/main/SJG_Grafana_Dashboard.json

**Comment by btbf** [comment]
@akyo3 ありがとうございます。
このjsonをインポートすると、瞬時にデータ取得が行われず一つ一つパネルを開いてデータソースを選択し直さなければならないようです。
原因究明と、json構造を見直しをお願いします。

![image](https://user-images.githubusercontent.com/37224549/178277098-100a0a8c-7714-45f7-a023-3d3e03ac5a65.png)

Grafana Version : 9.0.2

**Comment by akyo3** [comment]
おっしゃる通りdatasourceに誤りがあったため再度Pushし直しました。
こちらでは動作確認（既存Dashboardを削除し、Pushし直したjsonにて）できておりますのでお手隙の際に、ご確認ください。その他にあれば再度コメントください

https://raw.githubusercontent.com/akyo3/Extends-SJG-Knowledge/main/SJG_Grafana_Dashboard.json

**Comment by sakakibaraakio** [comment]
私の環境だと、新しい方でもインポート時にはデータの表示がされないようです。
（すみません最初のバージョンでも同様にインポート時表示が無かったのですが、自分の環境が原因だと思っていて報告が遅れました。）

おそらくですが、
全てのパネルにおいて、Query options内の　Max data points　と　Interval　が空になっているのが原因だと思われます。
ただデフォルトだと自動で数字が入っているはずなので、なぜ空なのかは検討がつかないですね…
![image](https://user-images.githubusercontent.com/69729884/178398127-da6725bd-6964-485b-bd33-56f15b708a4a.png)

**Comment by sakakibaraakio** [comment]
差し出がましいかもしれませんが、
一応私の方で、akyoさんのダッシュボードの各パネルにMax data pointsをオートで入力したものをアップしておきます。
https://raw.githubusercontent.com/sakakibaraakio/etc/main/SJG%3A%20Cardano-Node

**Comment by akyo3** [comment]
ありがとうございます！
これで問題なく他の人も表示されますかね？
（個人的には夕方確認します）

**Comment by btbf** [comment]
榊原さんの修正版で瞬時に表示されました！
内容を精査してまた報告します。

**Comment by akyo3** [comment]
@btbf 
お手数お掛けしますが、以下で再度試していただけますでしょうか？

https://raw.githubusercontent.com/akyo3/Extends-SJG-Knowledge/main/SJG_Grafana_Dashboard.json

**Comment by akyo3** [comment]
そもそももしかして出力方法が間違っているのかと思い、アプローチの仕方を変えてみました。出力後無加工です。
お手数ですが、こちらも併せてお試しいただけますと幸いです

https://raw.githubusercontent.com/akyo3/Extends-SJG-Knowledge/main/SJG_Cardano-Node-1657625805110.json

<img width="749" alt="スクリーンショット 2022-07-12 20 36 00" src="https://user-images.githubusercontent.com/80967103/178483244-94ad4e72-bf86-4685-80fd-fe44dae751f0.png">
<img width="763" alt="スクリーンショット 2022-07-12 20 46 20" src="https://user-images.githubusercontent.com/80967103/178483267-e63ec12c-738c-4732-bdf2-93ad8a64249f.png">
<img width="763" alt="スクリーンショット 2022-07-12 20 46 26" src="https://user-images.githubusercontent.com/80967103/178483291-53058fed-9b32-409a-af97-9be42e1ff1da.png">

**Comment by sakakibaraakio** [comment]
私の環境では2つとも即時表示されています。👍

**Comment by akyo3** [comment]
ありがとうございます！
現状問題となっているインポート後、すぐに反映表示されない問題は出力方法を変えたら問題なく誰がやってもインポートしても問題なさそうですね！（versionが9.0.2だったらかもしれませんが）

kaizen版はpluginVersionが7.5.3（9以前）でその時の出力方法だったのかと思ってます
もちろんjsonの書き方はあると思いますが、パネルを作成して出力するのにわざわざ編集して公開する手間を考えたら当時のversionで出力しているから今も特に問題なく表示されるのかなと思ってます

**Comment by btbf** [comment]
問題なくインポートできました！

**Comment by akyo3** [comment]
@btbf 
要望のあった見た目についてパネル構成を見直してみましたのでご確認ください

@btbf @sakakibaraakio 
以下(プラスα)のMetricsが発表されたときのノードバージョンについてご存じでしたら教えていただきたいです。(探したのですが、見つからず。。すみませんが、できれば記載されているLinkを教えていただけると助かります)
というのもパネルタイトルが長いのでうまく収まらず少し悩んでます

cardano_node_metrics_blockfetchclient_blockdelay_cdfOne

https://raw.githubusercontent.com/akyo3/Extends-SJG-Knowledge/main/SJG_Grafana_Dashboard.json
<img width="1676" alt="スクリーンショット 2022-08-08 22 32 17" src="https://user-images.githubusercontent.com/80967103/183431333-ae043889-600d-4a5c-b392-2c4b1f9157ff.png">
<img width="1676" alt="スクリーンショット 2022-08-08 22 32 34" src="https://user-images.githubusercontent.com/80967103/183431370-acd7a998-474b-497c-b37e-049848ebe895.png">
<img width="1676" alt="スクリーンショット 2022-08-08 22 32 46" src="https://user-images.githubusercontent.com/80967103/183431405-0bfdfbf1-71ff-40be-986d-9b49f3c6ea75.png">

**Comment by btbf** [comment]
こちらです
https://github.com/input-output-hk/cardano-node/releases/tag/1.31.0

https://github.com/input-output-hk/cardano-node/pull/2476

**Comment by akyo3** [comment]
ありがとうございます。外観など微修正しましたのでご確認ください。なにかあればお伝えください

https://raw.githubusercontent.com/akyo3/Extends-SJG-Knowledge/main/SJG_Grafana_Dashboard.json

<img width="1669" alt="スクリーンショット 2022-08-13 17 57 28" src="https://user-images.githubusercontent.com/80967103/184477071-f75b671d-2bc4-465d-97fd-6027f7f723ca.png">
<img width="1669" alt="スクリーンショット 2022-08-13 17 57 36" src="https://user-images.githubusercontent.com/80967103/184477084-8fa83d84-4be1-47ed-b5ca-1ea9beb3b3b1.png">
<img width="1669" alt="スクリーンショット 2022-08-13 17 57 43" src="https://user-images.githubusercontent.com/80967103/184477096-8b2f823d-8683-406b-b9e0-84e3849f0f24.png">

**Comment by btbf** [comment]
各パネルのタイトルを日本語表記にできますか？
