### ISSUE TITLE
提案　構築マニュアル　「Grafanaダッシュボードの改変」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#204]
現在マニュアルで使用されているGrafanaダッシュボードに一部手を加えてみました。
https://raw.githubusercontent.com/sakakibaraakio/etc/main/grafana_dashboard_JSG

 

> 変更点
> ・Mempool bytes、Mempool transactions、TXs processedの3つのパネルを削除
> →マニュアルのGrafana導入時には既にMempoolTraceがfalseになっていて、trueにした際の確認はgtoolで出来る為
> 
> ・Chain density % において、4.5以下の範囲で色が変化するように
> →普段は表示されませんが 4.5を下回る期間が出てくると赤い範囲が見えてきます。
> Graph(old)を使用してますが、閾値で色が変わる系の設定はstatを使った方が見た目が良いかもしれません。とりあえず今回はこちらで
> 
> ・メモリ使用量関連の単位を、bytes(SI)からbytes(IEC)に変更
> 
> ・新しくパネルを追加
> > Disk usage rate
> > →ディスク使用率、90%以上で赤文字に
> > 
> > Missed slot
> > →ミススロット
> > 
> > Swap Memory usage
> > →スワップメモリ使用量
> 

Disk usage rateのmetricsには、
`1 - node_filesystem_avail_bytes / node_filesystem_size_bytes{mountpoint="/"}`
を使用しています。全ての人の環境で正しく表示されるかは検証が必要かもしれません。

とりあえずの試しで作成したものなので、ご意見改良点などありましたら是非宜しくお願いします。
![aaa](https://user-images.githubusercontent.com/69729884/177020279-4612a926-e22f-4586-a648-c9a65a066b95.png)

**Comment by akyo3** [comment]
datasourceの"type": "prometheus"をPrometheus（Pを大文字）に編集して再度pushしてください。
それと置換するなら確か1360行目のcpu usaseのjobのprometheusは小文字で大丈夫です

**Comment by sakakibaraakio** [comment]
ありがとうございます。
勉強の為お尋ねしたいのですが、
>datasourceの"type": "prometheus"をPrometheus（Pを大文字）に編集
こちらは、どのような違いが生まれますか？

**Comment by akyo3** [comment]
失礼しました。昨日の夜中はそうだと思ってましたが、別要因だと思いますので調べます

**Comment by akyo3** [comment]
ちなみに榊原さんのダッシュボード私は見れないのですが、interval等で設定したjsonで再投稿してくれませんか？

**Comment by sakakibaraakio** [comment]
私のダッシュボードではMax data points と Intervalは既に設定されているはずですが、全く見えない形でしょうか？
パネルのEditを開いた時、Max data points と Intervalは表示されていますか？

**Comment by akyo3** [comment]
はい、全く見えない状況です。
> パネルのEditを開いた時、Max data points と Intervalは表示されていますか？
いいえ、表示されていません
<img width="1392" alt="スクリーンショット 2022-07-12 18 16 12" src="https://user-images.githubusercontent.com/80967103/178456518-910b8af8-7502-45d4-b40b-3ddafb4e0a32.png">

<img width="1381" alt="スクリーンショット 2022-07-12 18 19 52" src="https://user-images.githubusercontent.com/80967103/178456736-9fd6570c-1af6-4f70-9dc6-322bf8fdf09b.png">

**Comment by akyo3** [comment]
分かりました。後ほど展開します。

**Comment by sakakibaraakio** [comment]
ありがとうございます。akyoさんが変更したものはこちらでも即表示を確認できました。
ただ、
```
          "datasource": {
            "type": "Prometheus",
            "uid": "ZKZ6iIk7k"
          },
```
が含まれながら即表示がされるダッシュボードもあるので、
こうなると何が原因で表示されない状態が起きるのか、ますますわからなくなりますね…

BTBFさん、もしよろしければお手数ですがこのツリーの一番上にある
https://raw.githubusercontent.com/sakakibaraakio/etc/main/grafana_dashboard_JSG
のダッシュボードが正しく即表示されるか検証をお願いしてもいいでしょうか？

**Comment by akyo3** [comment]
こちらこそありがとうございます。
現状考えているのは以下です。
https://github.com/btbf/spojapanguild/issues/203#issuecomment-1181664088

参考記事
https://grafana.com/docs/grafana/latest/dashboards/export-import/

と、それとpanels配列のdatasourceにはtype、uidは不要なのかと考えてます

**Comment by sakakibaraakio** [comment]
ありがとうございます。
確かにtypeとuidの行は消すのが安定、という感じがしますね。
こちらは手動で消されましたか？

**Comment by akyo3** [comment]
もし良かったら榊原さんの作成したダッシュボードを以下のように出力してもらえますか？
https://github.com/btbf/spojapanguild/issues/203#issuecomment-1181664088

それで私がサクッと見れたら出力方法を上記のやり方にすれば問題ないような気がしてます


はい、手動です。エディターに貼り付けて置換しました。

**Comment by sakakibaraakio** [comment]
ありがとうございます。

https://raw.githubusercontent.com/sakakibaraakio/etc/main/grafana_dashboard_JSG2
出力しました。これも安定しそうですね。
ただ検証する人数がもう少し欲しいところですね…

**Comment by akyo3** [comment]
ありがとうございます！すぐ検証します！

**Comment by akyo3** [comment]
インポート後、すぐ表示されました！👏
![Screenshot_20220713-121813](https://user-images.githubusercontent.com/80967103/178643542-a8c625ba-27e8-4338-bc71-63c38a7fddd8.png)

**Comment by akyo3** [comment]
あと榊原さん、もしbtbfさんが問題なかったら（そうでなくとも）榊原さん作成のdashboard.jsonは、更新間隔がないようなので5秒で作成し直してアップしておくとインポートした人は楽かと思いました（また指摘事項があるかもしれないのでその時でもいいかも知れません…）

**Comment by sakakibaraakio** [comment]
ありがとうございます。早速修正しました。🙏

**Comment by akyo3** [comment]
ありがとうございます！
"refresh": "30s"に設定されているんですねー！
ちなみに30秒の方がいいのでしょうか？（5秒だと更新しすぎでしょうか？🧐

**Comment by sakakibaraakio** [comment]
prometheus自体が15秒毎にデータを吐き出さないので、不必要な通信を避ける意味で私は30秒に設定していますね。
ただこれは個人の好みで良いと思います。

**Comment by akyo3** [comment]
なるほど！ありがとうございます！
確かにそうですね！
scrape_interval:     15s

とても参考になりましたー！🙏
30秒で設定し直そうと思います
