### ISSUE TITLE
[バグ] グラフやチャートなど、図での説明が表示されない

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#21]
**バグについて説明してください。

構築マニュアル0、はじめに
http://49.12.225.142:8000/setup/0-start-guide/#0-3
の
「プール構成のイメージ」
や
4-3
http://49.12.225.142:8000/setup/4-bp-setup/#3
の
「ファイル転送」
などにおけるグラフ説明が表示されません。（もしくは表示が遅い）

左のメニューを使って、何かしらの項目から図がある項目へ飛ぶと表示されないようです。（URLで直接飛ぶと表示されます）

ページを更新する、もしくは現在開いている項目を左メニューで選択することで表示されますが、別ページに移ってから再度左メニューを使って戻るとまた表示されなくなります。
（私の環境だけだったらすみません）
chrome、firefoxで確認

グラフでの説明はあったほうが良いので、画像に置き換えるなどの手段を取ったほうが確実かもしれません。

**Comment by btbf** [comment]
テストサイトは現在プレビューモードで稼働しているため、
本番環境ではビルドされたページが生成されるので正常に表示されるはずです。
ご報告ありがとうございます。

**Comment by sakakibaraakio** [comment]
今現在、こちらの症状が再発しているようです。

**Comment by btbf** [comment]
fixed
