### ISSUE TITLE
修正　構築マニュアル5-5「stake.addr 	ステークアドレス秘密鍵」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#22]
■該当ページURL
http://49.12.225.142:8000/setup/5-generate-address/#5_1

■項番(あれば)
5-5.支払い用アドレスの作成

■修正前
stake.addr | ステークアドレス秘密鍵

■修正後
stake.skey | ステークアドレス秘密鍵

**Comment by btbf** [comment]
Fixed
Thank you!
