### ISSUE TITLE
修正提案　「#203　のGrafanaダッシュボードパネル」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#225]
■該当ページURL
https://docs.spojapanguild.net/setup/9-monitoring-tools-setup/#4grafana

10,左メニューからCreate + iconを選択 > Importをクリックします。
↓
10,左メニューのDashboards > +Importをクリックします。
___
https://github.com/btbf/spojapanguild/issues/203

・Node memory usageのメトリクス
```rts_gc_current_bytes_used/(1024*1024)```
↓
```rts_gc_current_bytes_used```
  
    
・`Uptime`    `Swap mem usage`     `Disk usage rate`の3つのパネルにて、
Standard options 内にある Min を 0にすることでゲージがきれいに表示されるかと思います。

**Comment by akyo3** [comment]
上記修正致しましたのでご確認ください！

**Comment by sakakibaraakio** [comment]
@btbf 
こちらの修正提案の一つ目、
______
■該当ページURL
https://docs.spojapanguild.net/setup/9-monitoring-tools-setup/#4grafana

10,左メニューからCreate + iconを選択 > Importをクリックします。
↓
10,左メニューのDashboards > +Importをクリックします。

____
の修正を再度提案させてもらってもいいですか？
