### ISSUE TITLE
1-Ubuntu初期設定－1-10.Chronyを設定する

### ISSUE THREAD

**Issue by AichiStakePool** [btbf/spojapanguild#23]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-10chrony

以下のように表示がバグっております。
プレビュー画面だから出ないのですかね？
![image](https://user-images.githubusercontent.com/99731543/154259448-a0605eec-bdc6-4909-a619-779285d81b6c.png)

**Comment by btbf** [comment]
Fixed
Thank you!
