### ISSUE TITLE
修正　運用マニュアル　KESの更新 「{% hint style="danger" %}　や　{% tabs %} {% tab title="ブロックプロデューサーノード" %}　などタグ？が表示されている」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#24]
■該当ページURL
http://49.12.225.142:8000/operation/kes-update/#2kes
http://49.12.225.142:8000/operation/kes-update/#5kes

■項番(あれば)
KESの更新　2.新しいKESファイルを生成
　　　　　  5.KESチェックプログラム実行

■修正前
2.新しいKESファイルを生成　
{% hint style="danger" %} kes.skey/kes.vkeyをエアギャップオフラインマシンのcnodeディレクトリにコピーします。

5.KESチェックプログラム実行
{% tabs %} {% tab title="ブロックプロデューサーノード" %} 

のように、本来囲いなどで表示されるところがタグ?コマンド?のように表示されています。

**Comment by btbf** [comment]
Fixed
