### ISSUE TITLE
更新：エアギャップマシンの作成(Mac)　macOS、VirtualBoxのバージョンアップのため、ドキュメント更新依頼

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#240]
■該当ページURL
https://docs.spojapanguild.net/setup/0-start-guide/#mac

◆更新ページURL

ttps://github.com/akyo3/Extends-SJG-Knowledge/blob/main/VirtualBox-Setup-on-MacOS.md

@btbf 
macOS版のエアギャップマシンの作成の手順を更新したので、問題なければアップしてください。

@sakakibaraakio
大変お手数ですが、簡単に目を通していただけますと助かります！

よろしくお願いします。

なお、先ほどノード起動できたことも確認できましたので、練習としても問題ないはずです。
![スクリーンショット 2022-11-05 19 43 40](https://user-images.githubusercontent.com/80967103/200116351-be4cbd90-46f8-4433-b56e-1640e84edd98.png)

**Comment by sakakibaraakio** [comment]
お疲れ様です。
`1- Ubuntuイメージファイルのダウンロード`
における、
`Ubuntuを入手する`
のリンク先が404になっているようです。

また、
最後の
```
本番運用で使用する際の注意点
本番運用で使用される場合は必ず「ネットワークアダプターを有効化」のチェックを外してください。
```
の項目は、マニュアルの
2-8. エアギャップオフラインマシンの作成
が終わってから行う、ということを記載していたほうが良いかもしれません。

**Comment by akyo3** [comment]
@sakakibaraakio
ご指摘ありがとうございます！修正対応完了しました。
https://github.com/akyo3/Extends-SJG-Knowledge/blob/main/VirtualBox-Setup-on-MacOS.md

**Comment by btbf** [comment]
@akyo3 
修正状況いかがでしょうか？

**Comment by akyo3** [comment]
すみません、急ぎ修正します！
