### ISSUE TITLE
提案　3-2. BPサーバーの設定変更（変数活用）

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#244]
■該当ページURL
https://docs.spojapanguild.net/setup/3-relay-bp-setup/#3-2-bp

文言：
■修正前
BPノードで使用する xxxx 番ポート(上記で表示された番号)の通信を許可する。

<リレーノード1のIP> の <>を除いてIPのみ入力してください。xxxxは上記で表示されたBPポート番号に置き換えてコマンドを実行してください。

■修正後
BPノードで使用するポートの通信を許可する。

<リレーノード1 or 2のIP> の <>を除いてIPのみ入力してください。

コマンド：（BPポートの変数があるので）

```
PORT=`grep "PORT=" $NODE_HOME/startBlockProducingNode.sh`
b_PORT=${PORT#"PORT="}
echo "BPポートは${b_PORT}です"
```

■修正前
xxxxx → ${b_PORT}
〜略〜

■修正後
BP(リレー1台の場合)
```
sudo ufw allow from <リレーノード1のIP> to any port ${b_PORT}
sudo ufw reload
```
BP(リレー2台の場合)

```
sudo ufw allow from <リレーノード1のIP> to any port ${b_PORT}
sudo ufw allow from <リレーノード2のIP> to any port ${b_PORT}
sudo ufw reload
```

**Comment by btbf** [comment]
Thank you!
