### ISSUE TITLE
提案　1-4.ファイアウォール有効化（変数活用）

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#245]
■該当ページURL
https://docs.spojapanguild.net/setup/1-ubuntu-setup/#1-4

文言：
■修正前
SSHポートを許可する
xxxxxを1-3で設定したSSHポートを指定してください

■修正後
SSHポートを許可する

コマンド：
■修正前
```sudo ufw allow xxxxx/tcp```

■修正後
```
PORT=`grep "Port" /etc/ssh/sshd_config`
s_PORT=${PORT#"Port"}
ssh_PORT=`echo ${s_PORT} | sed -e 's/[^0-9]//g'`
echo ${ssh_PORT}
```

```
sudo ufw allow ${ssh_PORT}/tcp
```

**Comment by btbf** [comment]
Thank you!
