### ISSUE TITLE
修正　運用マニュアル KESの更新　「6.エアギャップ：node.certファイルをBPのcnodeディレクトリへコピーする”注意”」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#25]
■該当ページURL
http://49.12.225.142:8000/operation/kes-update/#3nodecert

■項番(あれば)
3.node.cert生成

■修正前
6.エアギャップ：node.certファイルをBPのcnodeディレクトリへコピーする
の下の　注意　になにも書かれていないようです。

また
6.エアギャップ：node.certファイルをBPのcnodeディレクトリへコピーする
の箇所も
エアギャップのnode.certファイルをBPのcnodeディレクトリへコピーする
になるかと思われます。

**Comment by btbf** [comment]
Fixed
Thank you!
