### ISSUE TITLE
修正提案　プール運用マニュアル　サーバー間転送設定　事前設定　４，「作業内容の表記について」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#251]
■該当ページURL
https://docs.spojapanguild.net/operation/rsync-ssh/#4

■項番(あれば)
4.転送先を追加する場合

■修正前
転送先を追加する場合

・1-2のSSH設定ファイルに転送先を追記する
・1-3のrsync_ed25519.pubを転送先にコピーする
・2と3を実施する

■修正後
転送先を追加する場合

・1-2のSSH設定ファイルに転送先を追記する
・新しい転送先で2と3を実施する

_________
rsync_ed25519.pubを転送先にコピーする作業は、２の最初に含まれている為

**Comment by btbf** [comment]
#252
