### ISSUE TITLE
文言修正依頼　バトルの内容がPraos以前のままとなっている

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#256]
■該当ページURL
https://docs.spojapanguild.net/operation/start-guide/#_4

■修正前
スロットバトル(stolen)
ハイトバトル(Ghosted / missed)
　（ステーク量が少ないプールが有利）

■修正後
現在はステーク量の大小に関係なくランダムとなっているはずですので上記文言は削除でランダムになっている旨の記載に変更のほどよろしくお願いします。
https://discord.com/channels/747675500297584720/792575220719943720/1037367197116407959

**Comment by btbf** [comment]
Thanks!

**Comment by sakakibaraakio** [comment]
こちらの件、stolen　の項目にて
「ステーク量に応じて最大値が変化するため、ステーク量が小さいプールが有利とされています。」
との文言が残っているようです。
