### ISSUE TITLE
修正　よくある質問　ブロックログ関連　「スロットバトルの仕様変更による記述修正」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#259]
■該当ページURL
https://docs.spojapanguild.net/faq/blocklog/#q2

■項番(あれば)
Q2.ブロック生成に失敗しました。原因は何でしょうか？
stolenの場合

■修正前
しかしブロックチェーンに採用されるブロックは1スロット1ブロックなので、どのプールのブロックを採用するかを決定する際、ブロック生成時にプールが排出するVRF値が小さい方のブロックを採用する仕様となっております。

このVRF値は毎回異なるランダムな値を排出しますがステーク量に応じて最大値が変化するため、ステーク量が小さいプールが有利とされています。

■修正後
しかしブロックチェーンに採用されるブロックは1スロット1ブロックなので、どのプールのブロックを採用するかを決定する際、ブロック生成時にプールがランダムに排出するVRF値が小さい方のブロックを採用する仕様となっております。

**Comment by btbf** [comment]
Thanks!
