### ISSUE TITLE
修正　構築マニュアル1-9  「リレーノードのIPのみ受け付ける用に」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#26]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-8fail2ban

■項番(あれば)
1-9.ファイアウォールを構成する

■修正前
Prometheus-node-exporter用のポート12798・9100をリレーノードのIPのみ受け付ける用に設定してください。 

■修正後
Prometheus-node-exporter用のポート12798・9100をリレーノードのIPのみ受け付けるように設定してください。

**Comment by btbf** [comment]
Fixed
