### ISSUE TITLE
修正　構築マニュアル　10-9　「デタッチコマンド」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#261]
発見者：Muenさん
■該当ページURL
https://docs.spojapanguild.net/setup/10-blocklog-setup/#10-9

■項番(あれば)
10-9. スケジュールを取得する

■修正前
スケジュール取得が確認できたら Ctrl+c d でデタッチしてください。

■修正後
スケジュール取得が確認できたら Ctrl+b d でデタッチしてください。

**Comment by btbf** [comment]
Thanks!
