### ISSUE TITLE
修正　構築マニュアル　10-9　「リンク先が非公開版マニュアルになっている」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#262]
■該当ページURL
https://docs.spojapanguild.net/setup/10-blocklog-setup/#10-9

■項番(あれば)
10-9. スケジュールを取得する

■修正前
スケジュールの中にError: database is lockedがある場合は、よくある質問の[Q4.スケジュール取得時「Error: database is locked」が表示される](http://49.12.225.142:8000/faq/blocklog/)をご確認ください

■修正後
スケジュールの中にError: database is lockedがある場合は、よくある質問の[Q4.スケジュール取得時「Error: database is locked」が表示される](https://docs.spojapanguild.net/faq/blocklog/#q4error-database-is-locked/)をご確認ください

____
リンク先が
http://49.12.225.142:8000/faq/blocklog/
から
https://docs.spojapanguild.net/faq/blocklog/#q4error-database-is-locked/
に

**Comment by btbf** [comment]
Thanks!
