### ISSUE TITLE
貢献者の紹介ページ(URL)について

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#269]
ティッカー名を変更しました。
お手数ですが、URLの変更をよろしくお願いします。

①Linuxコマンド集
https://docs.spojapanguild.net/operation/command/?h=wyam

②FileZillaのセットアップ
https://docs.spojapanguild.net/operation/sftp/?h=wyam

③SJG貢献者
https://docs.spojapanguild.net/contributors/?h=wyam#_1

④Macの場合（エアギャップマシンの作成）
https://docs.spojapanguild.net/setup/air-gap-guid/?h=wyam#mac

Twitter：
https://twitter.com/AKYO_POOL

Cexplorer
[AKYO] AKYO🥁
https://jp.cexplorer.io/pool/pool1jsxk3ymqv2gdc6mhqk52544g2aun4zhq5wgx6n32l5s3jlne70n

**Comment by btbf** [comment]
Thanks!
