### ISSUE TITLE
[表示]ダークモードにおける図や文字の視認性について

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#27]
ダークモードだと、図での説明における矢印の色が黒のままなので少し見難くなっているようです。
![スクリーンショット 2022-02-19 035742](https://user-images.githubusercontent.com/69729884/154745554-36c7c9c8-1a3e-48ff-b72a-f07881cd8f9e.png)

また、紫文字もダークモードだと視認性に難が出てくるようです。
![スクリーンショット 2022-02-19 041431](https://user-images.githubusercontent.com/69729884/154747451-ab6cd06a-e49d-4f5b-93af-100b2216c9c5.png)

**Comment by btbf** [comment]
修正しました。
ご確認お願いします

**Comment by sakakibaraakio** [comment]
凄く見やすくなりました！修正作業ありがとうございます！

**Comment by btbf** [comment]
Fixed
