### ISSUE TITLE
[バグ]ページ遷移しない

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#270]
**バグについて説明してください。
ページ遷移しません。

**再現方法**について
動作を再現するための手順
1. '次のURLに移動します。https://docs.spojapanguild.net/operation/withdrawal/#1-stakeaddr
2. 1.payment.addrへ送金する方法は[こちら](https://docs.spojapanguild.net/operation/withdrawal/#2-1-paymentaddr)と2.任意のアドレスへ送金する方法は[こちら](https://docs.spojapanguild.net/operation/withdrawal/#2-2)の**こちら** をクリックします。

**期待される動作
予想される事象を簡潔明瞭に記述してください。
**こちら**には指定URLが埋め込まれているはずなので該当ページ（箇所）へ遷移する想定。

**スクリーンショット
該当する場合、問題の説明に役立つスクリーンショットを追加してください。
![スクリーンショット 2023-03-01 18 47 42](https://user-images.githubusercontent.com/80967103/222103441-28eb70fc-5894-411f-996d-c25789bba045.png)

■指定URLの向き先間違い（または修正漏れ）かと思いますのでご確認のほどよろしくお願いします。
`[こちら](https://docs.spojapanguild.net/operation/withdrawal/#2-1-paymentaddr)`
↓
`https://docs.spojapanguild.net/operation/withdrawal/#1-1-paymentaddr`

`[こちら](https://docs.spojapanguild.net/operation/withdrawal/#2-2)`
↓
`https://docs.spojapanguild.net/operation/withdrawal/#1-2`

また表記に関してですが、以下だと思いますので修正のほどよろしくお願いします。
①「1.payment.addrへ送金する方法はこちら」を
`1-1 payment.addrへ送金する方法`
②「2.任意のアドレスへ送金する方法はこちら」を
`1-2 任意のアドレスへ送金する方法`

ご確認いただけますと幸いです

**Comment by btbf** [comment]
Thanks!
