### ISSUE TITLE
修正　構築マニュアル7「変更する場合は、18.4の変更手順を実施してください。」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#28]
■該当ページURL
http://49.12.225.142:8000/setup/7-register-stakepool/

■項番(あれば)
該当ページ一番最初

■修正前
こちらの手順は初回プール登録時のみ有効です。
プール登録後にメタ情報、誓約、固定費、変動費、リレー情報を変更する場合は、[18.4](http://49.12.225.142:8000/setup/guide-how-to-build-a-haskell-stakepool-node/#184-prumetayamarginno)の変更手順を実施してください。
■修正後
こちらの手順は初回プール登録時のみ有効です。
プール登録後にメタ情報、誓約、固定費、変動費、リレー情報を変更する場合は、[プール情報(pool.cert)の更新](http://49.12.225.142:8000/operation/cert-update/)の変更手順を実施してください。

**Comment by btbf** [comment]
Fixed
