### ISSUE TITLE
修正　構築マニュアル7-2 「以下のスクリプトは例です。」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#29]
■該当ページURL
http://49.12.225.142:8000/setup/7-register-stakepool/#poolcert

■項番(あれば)
構築マニュアル７－２　プール登録証明書の作成　
pool.certを作成する
pool.cert作成時の注意点▼

■修正前
pool.certはプール登録証明書の役割を果たし、プール情報を記載します。
以下のスクリプトは例です。ご自身のプール運用設定値に変更してください。

※スクリプトは上に書かれているようです。

■修正後
pool.certはプール登録証明書の役割を果たし、プール情報を記載します。
上記のスクリプトは例です。ご自身のプール運用設定値に変更してください。

**Comment by btbf** [comment]
Fixed
