### ISSUE TITLE
アラート設定の「BPリレー接続監視」内のmetricsとURLリンク先変更によるアクセスができない

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#299]
①
■該当ページURL
https://docs.spojapanguild.net/operation/grafana-alert/#2-2bp

■項番(あれば)
アラート設定の「BPリレー接続監視」内のmetrics

■修正前
cardano_node_metrics_connectedPeers_int

■修正後
cardano_node_metrics_peers_connectedPeers_int
に変える必要あり。

②
■該当ページURL
https://docs.spojapanguild.net/operation/grafana-alert/#5

■項番(あれば)
[[3.通知先アプリの設定]](https://docs.spojapanguild.net/operation/grafana-alert/3)で取得した通知アプリごとのトークンIDやWebhookURLを入力する

■修正前
https://docs.spojapanguild.net/operation/grafana-alert/3

■修正後
https://docs.spojapanguild.net/setup/11-blocknotify-setup/#11-2

**Comment by btbf** [comment]
Thanks!
