### ISSUE TITLE
修正「SPOの必須スキル 0-1.SPOの必須スキル 「.」削除依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#3]
■該当ページURL
http://49.12.225.142:8000/#spo_2
http://49.12.225.142:8000/setup/0-start-guide/#0-1spo

■項番(あれば)
SPOの必須スキル
0-1.SPOの必須スキル

■修正前
サーバ管理スキル (運用および保守).

■修正後
サーバ管理スキル (運用および保守)

◆修正前最後尾の「.」不要

**Comment by btbf** [comment]
Fixed.
Thank you!
