### ISSUE TITLE
修正　構築マニュアル8　「Total Txが増加が確認できれば」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#30]
■該当ページURL
http://49.12.225.142:8000/setup/8.topology-setup/#_3

■項番(あれば)
8-P2Pトポロジー設定 
トポロジーファイルを生成する 　内の一番最後

■修正前
Total Txが増加が確認できれば、ブロックを作成する準備が出来ました。

■修正後
Total Txの増加が確認できれば、ブロックを作成する準備が出来ています。

**Comment by btbf** [comment]
Fixed
