### ISSUE TITLE
Prometheus.ymlの構文チェックコマンド追加依頼

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#305]
■該当ページURL
https://docs.spojapanguild.net/setup/9-monitoring-tools-setup/#9-2

■項番(あれば)
`prometheus.ymlを移動します`
の前に、以下のような文言とコマンドを追加

`設定ファイルの構文チェック`
```
sudo promtool check config prometheus.yml
```

Tip(緑か青のinfoのことです)
構文エラーなしの場合
```
Checking prometheus.yml
  SUCCESS: 0 rule files found
```
構文エラーの場合（一例）
```
Checking prometheus.yml
  FAILED: parsing YAML file prometheus.yml: yaml: line XX: did not find expected '-' indicator
```

------------------------------------

またTipとして？でもいいので、以下も記載しておいた方が良いかと思いましたのでよろしくお願いします。大体このような感じだと思います

Tip(緑か青のinfoのことです)
設定ファイルを移動したのち、設定ファイルの内容を修正する場合
```
sudo nano /etc/prometheus/prometheus.yml
```
> 修正したら、`Ctrl + O`で保存し、Enter。その後`Ctrl + X`で閉じる

修正後、設定ファイルの構文をチェックする
```
sudo promtool check config /etc/prometheus/prometheus.yml
```

Tip(緑か青のinfoのことです)
構文エラーなしの場合
```
Checking /etc/prometheus/prometheus.yml
  SUCCESS: 0 rule files found
```
構文エラーの場合（一例）
```
Checking /etc/prometheus/prometheus.yml
  FAILED: parsing YAML file /etc/prometheus/prometheus.yml: yaml: line XX: did not find expected '-' indicator
```

**Comment by btbf** [comment]
ver. 12.8.3で適用しました！
ありがとうございました。

**Comment by akyo3** [comment]
> ver. 12.8.3で適用しました！ ありがとうございました。

---

追加ありがとうございます！
https://docs.spojapanguild.net/setup/9-monitoring-tools-setup/#_1

ただ`既存の設定ファイルを更新する場合`の`prometheus.yml構文チェック`するコマンドは、PATHが違ってますので、修正お願いします。
ここでは移動後の設定ファイル、つまり/etc/prometheus配下のprometheus.ymlファイルの構文をチェックします。
![スクリーンショット 2023-07-18 18 00 01](https://github.com/btbf/spojapanguild/assets/80967103/99b688b3-29c6-4523-b9b9-cc08305f9338)


```
sudo promtool check config /etc/prometheus/prometheus.yml
```
また同様にTips内のコードブロックもPATHが違ってますので修正お願いします。

`構文エラーなしの場合`
```
Checking /etc/prometheus/prometheus.yml
  SUCCESS: 0 rule files found
```

`構文エラーの場合(一例)`
```
Checking /etc/prometheus/prometheus.yml
  FAILED: parsing YAML file /etc/prometheus/prometheus.yml: yaml: line XX: did not find expected '-' indicator
```

prometheus.ymlを開いて余分なスペースや記号の有無などを確認してください。
↓
`/etc/prometheus配下のprometheus.ymlを開いて余分なスペースや記号の有無などを確認してください。`

**Comment by akyo3** [comment]
> ver. 12.8.3で適用しました！ ありがとうございました。

---
度々すみません。
https://github.com/btbf/spojapanguild/issues/307#issue-1809537599

上記の場合、カレントディレクトリが`$HOME/prometheus.yml`でないとPATHが違うので怒られますので添付画像の赤線箇所を修正お願いしますｍｍ
![スクリーンショット 2023-07-18 18 44 14](https://github.com/btbf/spojapanguild/assets/80967103/40705099-e74a-4409-ba66-1400d4c0d331)

`prometheus.yml構文チェック`
```
sudo promtool check config $HOME/prometheus.yml
```

`戻り値確認`
`構文エラーなしの場合`
```
Checking /home/user/prometheus.yml
  SUCCESS: 0 rule files found
```
`構文エラーの場合(一例)`
```
Checking /home/user/prometheus.yml
  FAILED: parsing YAML file /home/user/prometheus.yml: yaml: line XX: did not find expected '-' indicator
```
※userは各自で設定したユーザー名です

```
/home/user/prometheus.ymlを開いて余分なスペースや記号の有無などを確認してください。 
```

**Comment by akyo3** [comment]
> ver. 12.8.3で適用しました！ ありがとうございました。

---
適用ありがとうございます！

修正順に並び替えます。

①
https://github.com/btbf/spojapanguild/issues/307#issue-1809537599

②
https://github.com/btbf/spojapanguild/issues/305#issuecomment-1639905380

③
https://github.com/btbf/spojapanguild/issues/305#issuecomment-1639839864

**Comment by btbf** [comment]
修正しました！

**Comment by akyo3** [comment]
> 修正しました！

ありがとうございます！

確かにここは`prometheus.yml`ですね！
あ、でも`$HOME/prometheus.yml`の方がいいかもしれません。
というかここに構文エラーだった場合の編集コマンドないですね。。

度々すみません！ｍｍ

```
prometheus.ymlを開いて余分なスペースや記号の有無などを確認してください。
※/home/user/prometheus.yml（userは各自で設定したユーザー名）
```
上記文言を以下のようにしてもらえませんでしょうか？

---
※/home/user/prometheus.yml（userは各自で設定したユーザー名）

構文エラーだった場合は、$HOME/prometheus.ymlを開いて余分なスペースや記号の有無などを確認し、編集してください。
```
sudo nano $HOME/prometheus.yml
```
> 修正したら、Ctrl + Oで保存し、Enter。その後Ctrl + Xで閉じる

**Comment by akyo3** [comment]
@btbf 

上記、良かったら修正、更新のほどよろしくお願いします！

**Comment by btbf** [comment]
> @btbf
> 
> 上記、良かったら修正、更新のほどよろしくお願いします！

修正しました！
