### ISSUE TITLE
修正　構築マニュアル10-1　「CNCLIはプールのブロック生成スケジュールを算出ツールを開発し」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#31]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-1-cncli

■項番(あれば)
10-1. CNCLIインストール

■修正前
AndrewWestbergさんによって開発されたCNCLIはプールのブロック生成スケジュールを算出ツールを開発し、Shelley期におけるSPOに革命をもたらしました。

■修正後
AndrewWestbergさんによって開発されたCNCLIはプールのブロック生成スケジュールを算出し、Shelley期におけるSPOに革命をもたらしました。

**Comment by btbf** [comment]
Fixed
