### ISSUE TITLE
文言追加依頼）DB同期ブートストラップ(Mithrilベータ版)の概要欄へ

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#323]
■該当ページURL
https://docs.spojapanguild.net/operation/mithril-client/

■項番(あれば)
概要

背景：
現状の記載だと全サーバで実施する可能性が高いと考えました。

現状の記載：
`Mithrilプロトコルはまだベータバージョンのため、ご自身の責任で実施してください。`

これを先日私が質問した際に回答していただいた以下のような文言を概要欄へ追加しませんか？
`メインネットでローンチされているので、複数リレーがあるうちの1つなら〜`

概要欄のイメージは以下となります。
![スクリーンショット 2023-10-09 10 51 46](https://github.com/btbf/spojapanguild/assets/80967103/9e224373-004e-42fb-a603-89ac2e90de60)

**Comment by btbf** [comment]
ご自身の責任でBP・リレーで実施しても構わないので、今のところ縛るつもりはありません。

**Comment by akyo3** [comment]
なるほど
最終的に問合せを考えた場合、提案したような文言が記載されていれば問合せコストが減ると思いましたが、承知しました

**Comment by btbf** [comment]
提案頂いた内容だとリレーに限定されているようなので、私が意図しているものとは異なるという意味合いです。
BPやリレーを新サーバーへ移行したり、DB破損で復旧したい場合には自己責任で実施してもいいですよという意図になりますが、このように記載したほうがいいでしょうか？

**Comment by akyo3** [comment]
ということは先日、Discordでお聞きした内容とは違うかと思いますが、いかがでしょうか？

https://discord.com/channels/747675500297584720/748032757074231347/1160674369442422875

**Comment by btbf** [comment]
あまり細かいことで議論するつもりはないですが、それは”例えば”です。
全ては”自己責任”という言葉でまとめているので、どのサーバーとかいうのは限定しません。

**Comment by akyo3** [comment]
なるほど、なにか問題があれば最終的に問合せがくるのはBTBFさん宛にだと思い、それだと大変だろうなと思ったので進言したまでです。
私はSJGドキュメントにおいて基本的に個人的にこう変えてほしいという想いで提案していることはそんなにないです、そういった書き方だと結局問合せが来ると思うので、提案しています。
以上です。ありがとうございます！

**Comment by btbf** [comment]
いつもありがとうございます！
