### ISSUE TITLE
疑問 構築マニュアル10　「cncli.shに記述するプールIDの形式について」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#33]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-2-sqlite3

■項番(あれば)
10-3. 依存ファイルダウンロード

■内容
「cncli.shファイルを修正します」
にてcncli.shファイル内に記述するプールIDを、stakepoolid.txtから取得していますが、
現在のマニュアルでは、stakepoolid.txt内のプールIDはbech32形式で記述されているように見えます。
http://49.12.225.142:8000/setup/7-register-stakepool/#4

cncli.sh内のコメントでは、hex方式でプールIDを記述してくださいと書かれているように見えますが、これは問題ないのでしょうか？

**Comment by btbf** [comment]
http://49.12.225.142:8000/setup/7-register-stakepool/#4
bech32とhexを出力するように修正しました。
ご確認お願いします。

**Comment by sakakibaraakio** [comment]
修正作業ありがとうございます。
一部修正点を見つけたのでお目通しお願いします。
#89

**Comment by btbf** [comment]
Fixed
