### ISSUE TITLE
提案　アップデートマニュアル「設定ファイル更新の際のバックアップ」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#340]
**問題点
ギルドのアップデートマニュアルは安全性の為にいつでも前のバージョンに戻せるよう構築されているが、
設定ファイルの変更が入る場合はそちらのバックアップも取っておいたほうが良い。

**解決策・提案**。
今回の場合（v8.7.2）では、
mainnet-conway-genesis.json
mainnet-config.json
の２ファイルを更新前に各環境でバックアップを取ることで、有事の際のダウングレードがよりスムーズにいくかもしれません。

**Comment by btbf** [comment]
@sakakibaraakio 
素晴らしいご提案ありがとうございます。

8.1.2→8.7.2はDBの再検証が発生し約6時間のダウンタイムが発生します。
RSYNCを使わない場合DBのバックアップを取っていませんが、この理論だどDBのバックアップも必要と考えますか？

現在のDB容量は約150GBで、ZStandard圧縮を使えば約50GBにまで抑えられることが検証できました。
DBもバックアップを取る場合は、最低100GBの残ディスク容量が必要かなと思うので、選択制として記載する感じがいいでしょうか？

**Comment by sakakibaraakio** [comment]
「DBを前バージョンに適応させる場合は、Mithrilを使用することでバックアップを取らずとも比較的スムーズにダウングレード可能」と漠然と考えていましたが、
・Mithrilがまだベータバージョンである事
・ノードのバージョンアップ時期によっては、MithrilのDBバージョンがアップグレード前のノードと一致していない可能性があること
・今後MithrilのDBバージョンの運用がどのようなルールになるか不明な事
を考慮すると、Mithrilの使用を標準の手段にするには問題が有る恐れがありそうですね。

DBのバックアップの保管がマニュアルの標準だと、それはそれでストレージ容量関連のトラブル発生に繋がりかねない点を考慮すると、
一概にDBバックアップをさせるのは避ける方向が良いですね。

「新Ver.ノードにトラブルが起きた時の為にDBバックアップを取りたい方（ディスク残り容量が100G以上必要）」
のような形で、展開させるタブの中で追加オプションの扱いで記載するのが適していそうですね。

  
  
「DBを安定板バージョンに戻す」というケースでMithrilを使用することの実用性がどれほどかの考慮が欠けていた中での提案だったことをお詫びします。

**Comment by btbf** [comment]
選択形式で掲載するようにします！
ご提案ありがとうございました。
