### ISSUE TITLE
修正　構築マニュアル10-4 「1行づつコマンドに貼り付けてください」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#35]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-4

■項番(あれば)
10-4. サービスファイル作成・登録

■修正前
1行づつコマンドに貼り付けてください

■修正後
1行ずつコマンドに貼り付けてください

**Comment by btbf** [comment]
Fixed
