### ISSUE TITLE
修正　構築マニュアル10-8　「このスロットのためにブロックを作った可能性e」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#36]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-8

■項番(あれば)
10-8. ブロックログを表示する

■修正前
スロットでスケジュールされているが、 cncli DB には記録されておらず他のプールがこのスロットのためにブロックを作った可能性e

■修正後
スロットでスケジュールされているが、 cncli DB には記録されておらず他のプールがこのスロットのためにブロックを作った可能性

**Comment by btbf** [comment]
Fixed
