### ISSUE TITLE
文言修正　SPO JAPAN GUILD DOCS 4-5.SPOBlockNotify移行手順

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#360]
■該当ページURL
https://docs.spojapanguild.net/operation/blocknotify-reinstall/#4

■修正前
他サービスの起動確認
└[blockNotifi](https://docs.spojapanguild.net/operation/blocknotify-reinstall/#blocknotifi)

■修正後
[blockNotify](https://docs.spojapanguild.net/operation/blocknotify-reinstall/#blocknotify)

添付画像赤矢印にエイリアスがあるといいと思いました
```
blocknotify
```

![スクリーンショット 2024-02-27 23 28 49](https://github.com/btbf/spojapanguild/assets/80967103/f6ea0244-6eba-4c0f-92da-2242b6add2c5)

**Comment by btbf** [comment]
#361 Done!
Thank you.

**Comment by akyo3** [comment]
> #361 Done! Thank you.

あ、タブのblocknotif
i
じゃなくて
y
の方が修正されてないです🙏
![Screenshot_20240228-152604](https://github.com/btbf/spojapanguild/assets/80967103/dc8a9fc1-e518-4ed8-a36e-a46d78aebd2e)
