### ISSUE TITLE
URL修正依頼

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#362]
■該当ページURL
https://docs.spojapanguild.net/setup/5-generate-address/#6

■修正前
テストネットタブの
[テストネット用口座](https://testnets.cardano.org/en/shelley/tools/faucet/)にあなたの支払い用アドレスをリクエストします。

URLが古いので修正後のURLへと修正お願いします。

■修正後

https://docs.cardano.org/cardano-testnet/tools/faucet/

**Comment by btbf** [comment]
Thank you.
Done!
