### ISSUE TITLE
修正　構築マニュアル10-8 「invalidの説明文」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#37]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-8

■項番(あれば)
10-8. ブロックログを表示する

■修正前
プールはブロックの作成に失敗しました。base64でエンコードされたエラーメッセージ。次のコードでデコードできます 'echo 

■修正後
プールはブロックの作成に失敗しました。base64でエンコードされたエラーメッセージがlogmonitorに表示されます。
次のコードでデコードできます 
 
`echo ＜エラーメッセージ＞| base64 -d | jq -r`

**Comment by btbf** [comment]
Fixed
