### ISSUE TITLE
修正　構築マニュアル10-9 「運用編へ　より後の記述について」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#38]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-9

■項番(あれば)
10-9. スケジュールを算出する

■修正前

> 運用編へ
> 
> 9-2. ブロック生成スケジュール算出のタイミングについて
> 
> 算出タイミングは、エポックスロットが約302400を過ぎてから次エポックのスケジュールを取得できるようになります。(次エポックの1.5日前)
> 取得するには、手動でノードを再起動します。(いろんな要素があって手動運用にしています)
> 
> 1エポックで1ブロック割り当てられるために必要な委任量の目安は以下の通りです。%は確率
> 1M 60%
> 2M 85%
> 3M 95%
> 
> プール開設時は、2エポック後から割り当てがスタートします。
> 303 プール登録
> 304 待機期間 次エポックスケジュール算出
> 305 委任有効 ブロック生成
> 306 報酬計算
> 307 報酬振り込み
> 
> 🏁 10. ブロック生成ステータスを通知する
> 
> 便利なツール
> 
> ブロックログDBに保存されるブロック生成ステータスをLINEまたはDiscordに通知することができます。
> 設定手順は[ブロック生成ステータス通知設定手順](http://49.12.225.142:8000/setup/10-blocklog-setup/block_notify/README.md)を参照してください。
> 

以下コメント：
「9-2. ブロック生成スケジュール算出のタイミングについて」
「10. ブロック生成ステータスを通知する」
の頭の数字は新マニュアルにおいては不要なようです。
また、ブロック生成ステータス通知設定手順のリンク先が404になっていて、
新マニュアルにはブロック生成ステータス通知設定手順が無いようです。

■修正後
ブロック生成スケジュール算出のタイミングについて

算出タイミングは、エポックスロットが約302400を過ぎてから次エポックのスケジュールを取得できるようになります。(次エポックの1.5日前)
取得するには、手動でノードを再起動します。(いろんな要素があって手動運用にしています)

1エポックで1ブロック割り当てられるために必要な委任量の目安は以下の通りです。%は確率
1M 60%
2M 85%
3M 95%

プール開設時は、2エポック後から割り当てがスタートします。
303 プール登録
304 待機期間 次エポックスケジュール算出
305 委任有効 ブロック生成
306 報酬計算
307 報酬振り込み

ブロック生成ステータスを通知する

便利なツール

ブロックログDBに保存されるブロック生成ステータスをLINEまたはDiscordに通知することができます。
 設定手順はブロック生成ステータス通知設定手順を参照してください。
 
 運用編へ

**Comment by btbf** [comment]
ブロック生成ステータス通知設定手順ページを作ってリンクする

**Comment by btbf** [comment]
文言修正
