### ISSUE TITLE
バグ-操作「サーバー選定について [プール構築手順]埋込リンク先に画面遷移しない」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#4]
**バグについて説明してください。
どのようなバグなのか、明確で簡潔な説明。

・期待される遷移先へ画面遷移しない。

**再現方法**について
動作を再現するための手順
1. 項目：「サーバー選定について」(http://49.12.225.142:8000/#_4)に移動します。
2. 最終行である文言　(サーバースペック要件は、[プール構築手順](http://49.12.225.142:8000/pool-setup/0-start-guide.md)に掲載しております)
の[プール構築手順]埋込リンクをクリックします。
3. 404というエラー表示

**期待される動作
予想される事象を簡潔明瞭に記述してください。

以下のリンク先を期待しているはずです。
「0-2.サーバースペック要件」
http://49.12.225.142:8000/setup/0-start-guide/#0-1spo

**スクリーンショット
添付済み。

**追加の状況**について
表記揺れしているので統一していただきたいです。
「手順」なのか「マニュアル」なのか。
項目でも使用している「マニュアル」で統一すると簡略化でき、よいのではと考える。

<img width="498" alt="スクリーンショット 2022-02-15 21 41 10" src="https://user-images.githubusercontent.com/80967103/154064178-758b507c-20b8-415c-989a-91e81266afbf.png">

**Comment by btbf** [comment]
Fixed.
Thank you!
