### ISSUE TITLE
修正　構築マニュアル　「寄付とクレジット　の番号」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#40]
■該当ページURL
http://49.12.225.142:8000/setup/99-donation-credit/

■項番(あれば)
ページ一番上のタイトル

■修正前
10.寄付とクレジット

■修正後
11.寄付とクレジット

またちなみにですが、構築マニュアル各ページの一番上のタイトルが、
１，２，３，５，６，９
にはタイトルの頭に数字がついていますが、それ以外だとついていないようです。

**Comment by btbf** [comment]
[10.ブロックログセットアップ](http://49.12.225.142:8000/setup/10-blocklog-setup/)
[＊寄付とクレジット](http://49.12.225.142:8000/setup/99-donation-credit/)
の間にページが増える可能性があるため、項番なし＊にします。

タイトル見出しに数字を入れました。
