### ISSUE TITLE
修正　運用マニュアル　運用ガイド 　「作業内容チェックリスト　の各リンク先」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#41]
■該当ページURL
http://49.12.225.142:8000/operation/start-guide/#_9

■項番(あれば)
作業内容チェックリスト

■修正前
エポック毎作業

    [次エポックのブロック生成スケジュールを算出する](http://49.12.225.142:8000/operation/start-guide/#_7)
    (320000スロットを超えてからエポック終了までに)

    [リレーノードトポロジーファイルの更新](http://49.12.225.142:8000/operation/start-guide/#_6)
    
3か月毎作業

    [KES更新(1-KESの更新)](http://49.12.225.142:8000/operation/start-guide/1-oparation-kes.md)

■修正後
エポック毎作業

    [次エポックのブロック生成スケジュールを算出する](http://49.12.225.142:8000/operation/start-guide/#_11)
    (320000スロットを超えてからエポック終了までに)

    [リレーノードトポロジーファイルの更新](http://49.12.225.142:8000/operation/start-guide/#_10)

3か月毎作業

    [KES更新(1-KESの更新)](http://49.12.225.142:8000/operation/kes-update/)

**Comment by btbf** [comment]
Fixed
