### ISSUE TITLE
修正　運用マニュアル　プール情報の更新 　「 複数のリレーノードを構成する記述方法　のリンク先」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#42]
■該当ページURL
http://49.12.225.142:8000/operation/cert-update/

■項番(あれば)
登録証明書トランザクションを作成する

■修正前
複数のリレーノードを設定する場合は [複数のリレーノードを構成する記述方法](http://49.12.225.142:8000/operation/pool-setup/7-register-stakepool.md#2) を参考にパラメーターを指定して下さい。

■修正後
複数のリレーノードを設定する場合は [複数のリレーノードを構成する記述方法](http://49.12.225.142:8000/setup/7-register-stakepool/#poolcert) を参考にパラメーターを指定して下さい。

**Comment by btbf** [comment]
Fixed
