### ISSUE TITLE
修正　ノード運用マニュアル　ノードアップデート 　「約10分～15分ほどで同期完了見込み」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#43]
■該当ページURL
http://49.12.225.142:8000/operation/node-update/#1-5

■項番(あれば)
1-5.ノード起動
ノード状況を確認する

■修正前
約10分～15分ほどで同期完了見込み

具体的な時間は不明ですが、同期完了までには数時間が必要になると思われます。

**Comment by btbf** [comment]
Fixed
