### ISSUE TITLE
修正　運用マニュアル　資金引き出し 「lovelaces」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#44]
■該当ページURL
http://49.12.225.142:8000/operation/withdrawal/#1-paymentaddr
http://49.12.225.142:8000/operation/withdrawal/#2-1-paymentaddr
■項番(あれば)
1 Payment.addrからの引き出し
2-1 payment.addrへ送金する方法
■修正前
1 Payment.addrからの引き出し
lovelaces形式で送信する金額を設定します。1 ADA = 1,000,000 lovelaces で覚えます。

2-1 payment.addrへ送金する方法
1 ADA = 1,000,000 lovelaces.と覚えましょう 
■修正後
1 Payment.addrからの引き出し
lovelace形式で送信する金額を設定します。1 ADA = 1,000,000 lovelaceで覚えます。

2-1 payment.addrへ送金する方法
1 ADA = 1,000,000 lovelaceと覚えましょう

**Comment by btbf** [comment]
fixed
