### ISSUE TITLE
修正　運用マニュアル　資金引き出し 「支払いとステークの秘密鍵の両方を使用していトランザクションに署名します。」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#45]
■該当ページURL
http://49.12.225.142:8000/operation/withdrawal/#2-1-paymentaddr
http://49.12.225.142:8000/operation/withdrawal/#2-2

■項番(あれば)
2-1 payment.addrへ送金する方法
2-2 任意のアドレスへ送金する方法

■修正前
2-1 payment.addrへ送金する方法
支払いとステークの秘密鍵の両方を使用していトランザクションに署名します。

2-2 任意のアドレスへ送金する方法
支払いとステークの秘密鍵の両方を使用していトランザクションに署名します。
■修正後
2-1 payment.addrへ送金する方法
支払いとステークの秘密鍵の両方を使用してトランザクションに署名します。

2-2 任意のアドレスへ送金する方法
支払いとステークの秘密鍵の両方を使用してトランザクションに署名します。

**Comment by btbf** [comment]
Fixed
