### ISSUE TITLE
修正提案　運用マニュアル　資金引き出し 　「このアドレスには取引手数料を支払うための残高が必要です。」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#46]
■該当ページURL
http://49.12.225.142:8000/operation/withdrawal/#2-1-paymentaddr

■項番(あれば)
2-1 payment.addrへ送金する方法

■修正前
報酬の移動先となるアドレスを設定します。このアドレスには取引手数料を支払うための残高が必要です。

■修正後
報酬の移動先にpayment.addrを設定します。payment.addrには取引手数料を支払うための残高が必要です。

**Comment by btbf** [comment]
Fixed
