### ISSUE TITLE
修正　運用マニュアル　プール廃止 　「プールが引退できる最も早くて最も遅い引退エポックを見つけます。」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#47]
■該当ページURL
http://49.12.225.142:8000/operation/pool-retire/#1

■項番(あれば)
1.リタイア処理

■修正前
プールが引退できる最も早くて最も遅い引退エポックを見つけます。

■修正後
プールが最も早く引退できるエポックと最も遅い引退エポックを見つけます。

**Comment by btbf** [comment]
Fixed
