### ISSUE TITLE
修正 「BPのセットアップ　 コマンド入力ではないためコピーは不要(3ファイルが必要な記載箇所について)」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#49]
■該当ページURL
http://49.12.225.142:8000/setup/4-bp-setup/#5bp

■項番(あれば)
BPのセットアップ
　5.BPノードとして再起動
　　注意事項

■修正前
コピーして入力してもらう仕様となっている。
kes.skey
vrf.skey
node.cert

■修正後
コマンド入力しないので注意書き程度で問題ないのでコピーさせず、「注意事項」下部に記載のみでよいと思います。

**Comment by btbf** [comment]
Fixed
