### ISSUE TITLE
誤字 「5.プール運営で使用するアドレスを作成する 1.プロトコルパラメータの取得　重要なアドバス」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#50]
■該当ページURL
http://49.12.225.142:8000/setup/5-generate-address/#1

■項番(あれば)
5.プール運営で使用するアドレスを作成する
　1.プロトコルパラメータの取得

■修正前
運用上のセキュリティに関する重要なアドバス

■修正後
運用上のセキュリティに関する重要なアドバイス

**Comment by btbf** [comment]
Fixed
