### ISSUE TITLE
修正 「ステークプールの登録　表記揺れ　lovelace単位　桁区切りとするか否か」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#51]
■該当ページURL
http://49.12.225.142:8000/setup/7-register-stakepool/#2

■項番(あれば)
2.プール登録証明書の作成
　
■修正前
lovelace単位での桁区切りについて

以下の箇所では桁区切りされてますが、
http://49.12.225.142:8000/setup/6-register-stakeaddress/#2
　2.ステークアドレスを登録する
　　2,000,000 lovelace (2ADA)

以下の箇所では桁区切りされていません。
http://49.12.225.142:8000/setup/7-register-stakepool/#2
　minPoolCost(固定費)は 340000000 lovelace (340 ADA)です。

■修正後
桁区切りとする場合は、以下となるかと思います。

minPoolCost(固定費)は 340,000,000 lovelace (340 ADA)です。

**Comment by btbf** [comment]
Fixed
