### ISSUE TITLE
修正 「スクリプトファイルの作成 文言修正依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#53]
■該当ページURL
http://49.12.225.142:8000/setup/8.topology-setup/#_1

■項番(あれば)
スクリプトファイルの作成
　注意

■修正前
以下は、リレーノードのパブリックIPとノードポートに合わせる
CNODE_PORT=6000
CNODE_HOSTNAME="xxx.xxx.xxx.xx"
※26行目の"CHANGE ME"は変更しないでください

■修正後
CNODE_HOSTNAMEの「＊」はリレーのパブリックIP(静的)アドレスに置き換えて下さい
ポート番号を6000から変更している場合は修正してください
※26行目の"CHANGE ME"は変更しないでください

**Comment by btbf** [comment]
Fixed
