### ISSUE TITLE
修正 「スクリプトファイルの作成 Cronジョブの設定　スクリプトを実行した時間(分)を指定して下さい　の指定箇所について」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#54]
■該当ページURL
http://49.12.225.142:8000/setup/8.topology-setup/#_1

■項番(あれば)
Cronジョブの設定
　注意

■修正前
以下のコードは毎時22分に実行されるように指定しています。(上記スクリプトを実行した時間(分)を指定して下さい)

■修正後
以下のコードは毎時22分に実行されるように指定しています。

◆理由：読み手は指定箇所が不明と考えます。
指定箇所を明確にしておくとより良いのではないかと思いました。
また特に指定する必要がないのであれば以下の文言は削除でもいいかと思いました。

(上記スクリプトを実行した時間(分)を指定して下さい)

**Comment by btbf** [comment]
Fixed
