### ISSUE TITLE
修正 「トポロジーファイルを生成する　 文言修正依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#55]
■該当ページURL
http://49.12.225.142:8000/setup/8.topology-setup/#_3

■項番(あれば)
トポロジーファイルを生成する
　注意

■修正前
以下は、BPのパブリックIPとノードポートに書き換えてからコマンドを実行する
BLOCKPRODUCING_IP=***.***.***
BLOCKPRODUCING_PORT=6000

■修正後
BLOCKPRODUCING_IPの「＊」はBPのパブリックIP(静的)アドレスに置き換えて下さい
ポート番号を6000から変更している場合は修正してください

**Comment by btbf** [comment]
Fixed
