### ISSUE TITLE
修正 「トポロジーファイルを生成する　 Total Txが増加が」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#56]
■該当ページURL
http://49.12.225.142:8000/setup/8.topology-setup/#_3

■項番(あれば)
トポロジーファイルを生成する
　おめでとうございます！

■修正前
Total Txが増加が確認できれば、ブロックを作成する準備が出来ました。

■修正後
Total Txの増加が確認できれば、ブロックを作成する準備が出来ました。

**Comment by btbf** [comment]
Fixed
