### ISSUE TITLE
修正 「9.監視ツールセットアップ　 aptへ変更依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#57]
■該当ページURL
http://49.12.225.142:8000/setup/9-monitoring-tools-setup/#9

■項番(あれば)
prometheusインストール
grafanaインストール

★BP/リレー
■修正前
sudo apt-get install -y prometheus-node-exporter

sudo apt-get install -y prometheus prometheus-node-exporter
sudo apt-get update && sudo apt-get install -y grafana

■修正後
sudo apt install -y prometheus-node-exporter

sudo apt install -y prometheus prometheus-node-exporter
sudo apt update && sudo apt install -y grafana

◆オプションの有無については調べてません。

**Comment by btbf** [comment]
Fixed
