### ISSUE TITLE
修正 「2.定義ファイルの作成 文言修正依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#58]
■該当ページURL
http://49.12.225.142:8000/setup/9-monitoring-tools-setup/#2

■項番(あれば)
2.定義ファイルの作成
　注意

■修正前
***.***.***.***はBPのパブリックIPアドレスに書き換えて、コマンドを送信してください。

■修正後
targets:の「＊」は、BPのパブリックIP(静的)アドレスに置き換えて下さい

**Comment by btbf** [comment]
Fixed
