### ISSUE TITLE
修正 「3-1. Topologyファイルの修正 文言修正依頼　パプリックIP(静的)アドレス」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#59]
■該当ページURL
http://49.12.225.142:8000/setup/3-relay-bp-setup/#3-1-topology

■項番(あれば)
topology.json とは？

■修正前
リレーノードでは、パプリックノード (IOHKや他のリレーノード) 及び、自身のブロックプロデューサーノード情報を記述します。

「＊」はパプリックIP(静的)アドレスに置き換えて下さい

「＊」はBPのパプリックIP(静的)アドレスに置き換えて下さい

「＊」はリレーのパプリックIP(静的)アドレスに置き換えて下さい
■修正後
リレーノードでは、パブリックノード (IOHKや他のリレーノード) 及び、自身のブロックプロデューサーノード情報を記述します。

「＊」はパブリックIP(静的)アドレスに置き換えて下さい

「＊」はBPのパブリックIP(静的)アドレスに置き換えて下さい

「＊」はリレーのパブリックIP(静的)アドレスに置き換えて下さい

◆パプリックではなくパブリック

**Comment by btbf** [comment]
Fixed
