### ISSUE TITLE
修正 「2.プール登録証明書の作成　パプリックIPへ書き換え」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#60]
■該当ページURL
http://49.12.225.142:8000/setup/7-register-stakepool/#2

■項番(あれば)
リレーの記述について

■修正前
[***.***.***]をリレーノードのパプリックIPへ書き換え

■修正後
[***.***.***]をリレーノードのパブリックIP(静的)アドレスへ書き換え

**Comment by btbf** [comment]
Fixed
