### ISSUE TITLE
修正 「3.ノード設定ファイルの更新 表記揺れ　パブリックIP」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#61]
■該当ページURL
http://49.12.225.142:8000/setup/9-monitoring-tools-setup/#3

■項番(あれば)
ファイアウォールの設定を確認してください

■修正前
ファイアウォールを設定している場合は、ブロックプロデューサーノードにて9100番と12798番ポートをリレーノード1のパブリックIP指定で開放して下さい。

■修正後
ファイアウォールを設定している場合は、ブロックプロデューサーノードにて9100番と12798番ポートをリレーノード1のパブリックIP(静的)アドレス指定で開放して下さい。

**Comment by btbf** [comment]
Fixed
