### ISSUE TITLE
修正 「10-1. CNCLIインストール　文言修正依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#62]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-1-cncli

■項番(あれば)
10-1. CNCLIインストール
　CNCLIについて

■修正前
AndrewWestbergさんによって開発されたCNCLIはプールのブロック生成スケジュールを算出ツールを開発し、Shelley期におけるSPOに革命をもたらしました。

■修正後
CNCLIは、プールのブロック生成スケジュールを算出できるツールです。
開発者であるAndrewWestbergさんは、Shelley期におけるSPOに革命をもたらしました。

◆開発された、開発し　が重複しているように感じたため
また強調したい文言はAndrewさんではなくCNCLIだと思ったため

**Comment by btbf** [comment]
#31
