### ISSUE TITLE
修正 プール運用マニュアルー運用ガイド

### ISSUE THREAD

**Issue by AichiStakePool** [btbf/spojapanguild#63]
■該当ページURL
http://49.12.225.142:8000/operation/start-guide/
まとめて４つ記載します。

**★★★★★★★★★★★★　１　★★★★★★★★★★★★**

■修正前
スロットバトル(stolen)

他プールと同じスロットに割り当てられた際に発生 vrf値によるサイコロゲームが行われ出た目の小さいプールのブロックが採用されます。（ステーク量が少ないプールが有利）

■修正後（**改行をする**）
スロットバトル(stolen)

他プールと同じスロットに割り当てられた際に発生
vrf値によるサイコロゲームが行われ出た目の小さいプールのブロックが採用されます。（ステーク量が少ないプールが有利）

**★★★★★★★★★★★★　２　★★★★★★★★★★★★**

■修正前
KES＝key-Evolving Signatures

■修正後（改行をする）
KES＝**K**ey-Evolving Signatures

**★★★★★★★★★★★★　３　★★★★★★★★★★★★**

■修正前
VRF=Verifiable random function

■修正後（改行をする）
VRF=Verifiable **R**andom **F**unction

**★★★★★★★★★★★★　４　★★★★★★★★★★★★**

Kesとは？の項目において
Ouroboros Praosとウロボロスプラオスを統一する

**Comment by btbf** [comment]
Fixed
