### ISSUE TITLE
修正 「10-7. ログファイル生成設定　logmonitor(5分後に遅延起動)」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#64]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-7

■項番(あれば)
10-7. ログファイル生成設定
　確認

■修正前
logmonitor(5分後に遅延起動)

■修正後
logmonitor(20秒後に遅延起動)

**Comment by btbf** [comment]
表記変更
