### ISSUE TITLE
修正 「プログラムのログ画面を確認します　以下表示なら正常です。」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#65]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-7

■項番(あれば)
プログラムのログ画面を確認します

■修正前
validate
以下表示なら正常です。
leaderlog
以下の表示なら正常です。
logmonitor
以下の表示なら正常です。

■修正後
validate
以下の表示なら正常です。
leaderlog
以下の表示なら正常です。
logmonitor
以下の表示なら正常です。

◆３つのタブで上記文言を統一すると良いかと思いました。

**Comment by btbf** [comment]
Fixed
