### ISSUE TITLE
修正 「10-8. ブロックログを表示する　エイリアス設定について」 

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#66]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-8

■項番(あれば)
10-8. ブロックログを表示する
　便利な設定

■修正前
echo alias blocks="$NODE_HOME/scripts/blocks.sh" >> $HOME/.bashrc

■修正後
echo alias blocks="'cd $NODE_HOME/scripts; ./blocks.sh'" >> $HOME/.bashrc

**Comment by btbf** [comment]
Fixed
