### ISSUE TITLE
誤字 「10-8. ブロックログを表示する　Blocks Tool　プログラム内文言修正後、画像差替え依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#67]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-8

■項番(あれば)
便利な設定

■修正前
BLOCKS TOOL @ Developed by Guild Operators & Cutomized by BTBF
<img width="839" alt="スクリーンショット 2022-02-20 15 36 26" src="https://user-images.githubusercontent.com/80967103/154831687-8cf2d9bf-c4f5-43b1-94c0-133ba0259130.png">

■修正後
BLOCKS TOOL @ Developed by Guild Operators & Customized by BTBF

◆プログラム内で文言修正した後、修正した画像の差替え依頼

**Comment by btbf** [comment]
fixed
(envファイル対応適用プログラムを実行したらblocks.shも更新される)
