### ISSUE TITLE
誤字修正 「10-8. ブロックログを表示する 」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#68]
■該当ページURL

■項番(あれば)
10-8. ブロックログを表示する
　便利な設定
　　ブロックステータス

■修正前
・Missed | スロットでスケジュールされているが、 cncli DB には記録されておらず他のプールがこのスロットのためにブロックを作った可能性e

・Ghosted | ブロックは作成されましたが「Orpah(孤立ブロック)」となっております。 スロットバトル・ハイトバトルで敗北したか、ブロック伝播の問題で有効なブロックになっていません

■修正後
Missed | スロットでスケジュールされているが、 cncli DB には記録されておらず他のプールがこのスロットのためにブロックを作った可能性

Ghosted | ブロックは作成されましたが「Orphan(孤立ブロック)」となっております。 スロットバトル・ハイトバトルで敗北したか、ブロック伝播の問題で有効なブロックになっていません
◆Orphanと記載しましたが、PoolToolではOrphansとなってます。ご判断ください。

◆◆なおプログラムでの表示は見れていません。

**Comment by btbf** [comment]
Fixed
