### ISSUE TITLE
修正 「10-9. スケジュールを算出する　(5分後に遅延起動)」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#69]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-9

■項番(あれば)
10-9. スケジュールを算出する
　ノードを再起動する

■修正前
cnode-logmonitor.service(5分後に遅延起動)

■修正後
cnode-logmonitor.service(20秒後に遅延起動)

**Comment by btbf** [comment]
Fixed
