### ISSUE TITLE
修正「10-8. ブロックログを表示する　太字ではない」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#71]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-8

■項番(あれば)
10-8. ブロックログを表示する

■修正前
10-8. ブロックログを表示する

■修正後
10-8. ブロックログを表示する

この項目だけ太字ではない

**Comment by btbf** [comment]
Fixed
