### ISSUE TITLE
修正「 9-2. ブロック生成スケジュール算出のタイミングについて　9−1.を飛ばして9−2.となっている」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#72]
■該当ページURL
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-9

■項番(あれば)
9-2. ブロック生成スケジュール算出のタイミングについて

■修正前
9-2. ブロック生成スケジュール算出のタイミングについて

■修正後
10-9-1. ブロック生成スケジュール算出のタイミングについて

■その他
10-9-1. ブロック生成スケジュール算出のタイミングについて
が見出し設定＆リンク設定となっていない

しかし、ここは「便利なツール」や「便利な設定」みたいな枠組みで良いと思います。

**Comment by btbf** [comment]
#38
