### ISSUE TITLE
修正「 10. ブロック生成ステータスを通知する　リンクなし、見出し設定となっていない」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#73]
■該当ページURL

■項番(あれば)
 10. ブロック生成ステータスを通知する

■修正前
 10. ブロック生成ステータスを通知する

■修正後
 10. ブロック生成ステータスを通知する　（リンク）

■その他
「便利なツール」の「ブロック生成ステータス通知設定手順」の遷移先なし。
ページ実装後、遷移することを期待。

**Comment by btbf** [comment]
Fixed
