### ISSUE TITLE
修正「スケジュール算出　文言修正依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#75]
■該当ページURL
http://49.12.225.142:8000/operation/start-guide/#_11

■項番(あれば)
スケジュール算出
　概要

■修正前
エポック終了までに次のスロットリーダースケジュールを算出し、事前に把握することを推奨します。
スロットリーダー算出にはノードを再起動を伴うため、スケジュールが分からない状態でノード再起動するのはリスクを伴います。

■修正後
エポック終了までに次のスロットリーダースケジュールを算出し、事前に把握することを推奨します。
スロットリーダースケジュールを算出するにあたりノードを再起動するため、スケジュールが分からない状態でノードを再起動するのはリスクを伴うため事前に把握しておきましょう。

もしくは

次のスロットリーダースケジュールはエポック終了までにノードを再起動することによって算出され、把握できます。(1.5日前から算出可能)
エポックが切り替わった後でも算出できますが、スケジュールが分からない状態でのノード再起動となり、リスクを伴うため事前に把握することを推奨します。

**Comment by btbf** [comment]
Fixed
