### ISSUE TITLE
修正「スケジュール算出　Leaderlogの状態確認の説明ですがValidationの説明となっている」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#76]
■該当ページURL
http://49.12.225.142:8000/operation/start-guide/#_11

■項番(あれば)
スケジュール算出
　リーダーログの状態を確認する

■修正前
「CNCLI Block Validation started」 の表示があればスケジュール算出中

■修正後
「CNCLI Leaderlog started」 の表示があればスケジュール算出中

**Comment by btbf** [comment]
Fixed
