### ISSUE TITLE
修正「10-9. スケジュールを算出する　スケジュール算出　内容重複」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#77]
■修正依頼

10.ブロックログセットアップの項目の10-9. スケジュールを算出する
http://49.12.225.142:8000/setup/10-blocklog-setup/#10-9
と、
運用ガイド「スケジュール算出」
http://49.12.225.142:8000/operation/start-guide/#_11
の内容が重複しています。

運用ガイド「スケジュール算出」では概要を残し、
「10-9. スケジュールを算出する」へ遷移するように埋込リンクを設定すると良いかと思います。

**Comment by btbf** [comment]
Fixed
