### ISSUE TITLE
修正「1-9.ファイアウォールを構成する 末尾の＃の必要性が不明」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#8]
■該当ページURL
http://49.12.225.142:8000/setup/1-ubuntu-setup/#1-9

■項番(あれば)
1-9.ファイアウォールを構成する

■修正前
SSH接続用のポート22番(または設定したランダムなポート番号 #)

■修正後
SSH接続用のポート22番(または設定したランダムなポート番号)

◆最後尾の＃の必要性が不明。

**Comment by btbf** [comment]
Fixed.
Thank you!
