### ISSUE TITLE
修正「2. エアギャップマシンアップデート　(実施は1回のみでOK)」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#81]
■該当ページURL
http://49.12.225.142:8000/operation/node-update/#2

■項番(あれば)
2. エアギャップマシンアップデート

■修正前
エアギャップマシン用にバイナリファイルをコピーする(実施は1回のみでOK)

■修正後
エアギャップマシン用にバイナリファイルをコピーする

◆(実施は1回のみでOK)が誤解を招きそうなため削除依頼
一回しかやってはいけないの？など

**Comment by btbf** [comment]
Fixed
