### ISSUE TITLE
修正「3.CNCLIバージョンアップ　logmonitor(5分後に遅延起動) 」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#82]
■該当ページURL
http://49.12.225.142:8000/operation/node-update/#3cncli

■項番(あれば)
サービス起動を確認する
　ヒント

■修正前
logmonitor(5分後に遅延起動) 

■修正後
logmonitor(20秒後に遅延起動)

**Comment by btbf** [comment]
Fixed
