### ISSUE TITLE
修正「1 Payment.addrからの引き出し　lovelaces」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#83]
■該当ページURL
http://49.12.225.142:8000/operation/withdrawal/#1-paymentaddr

■項番(あれば)
1 Payment.addrからの引き出し

■修正前
lovelaces形式で送信する金額を設定します。1 ADA = 1,000,000 lovelaces で覚えます。

■修正後
Lovelace形式で送信する金額を設定します。1 ADA = 1,000,000 Lovelace で覚えます。

**Comment by btbf** [comment]
#44
