### ISSUE TITLE
修正「1 Payment.addrからの引き出し　文言削除依頼」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#84]
■該当ページURL
http://49.12.225.142:8000/operation/withdrawal/#1-paymentaddr

■項番(あれば)
1 Payment.addrからの引き出し
　ファイル転送

■修正前
BPのtx.raw` をエアギャップマシンのcnodeディレクトリにコピーします。

■修正後
BPのtx.rawをエアギャップマシンのcnodeディレクトリにコピーします。

◆tx.rawを太字としたかったのではないかなと思います。
その場合は太字としてください。

**Comment by btbf** [comment]
Fixed
