### ISSUE TITLE
修正「2-1 payment.addrへ送金する方法　2-2 任意のアドレスへ送金する方法　支払いとステークの秘密鍵の両方を使用していトランザクションに署名します。」

### ISSUE THREAD

**Issue by akyo3** [btbf/spojapanguild#86]
■該当ページURL
http://49.12.225.142:8000/operation/withdrawal/#2-1-paymentaddr
http://49.12.225.142:8000/operation/withdrawal/#2-2

■項番(あれば)

■修正前
支払いとステークの秘密鍵の両方を使用していトランザクションに署名します。

■修正後
支払いとステークの秘密鍵の両方を使用してトランザクションに署名します。

もしくは

payment.skey、stake.skeyを使用してトランザクションに署名します。

**Comment by btbf** [comment]
#45
