### ISSUE TITLE
修正　構築マニュアル7-4 「プール登録確認コマンド　および　allpoos」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#89]
■該当ページURL
http://49.12.225.142:8000/setup/7-register-stakepool/#4

■項番(あれば)
4. プール登録確認

■修正前
以下のコマンドを実行し、赤文字の戻り値があればブロックチェーンに登録されています
ブロックプロデューサーノード

cardano-cli query stake-pools --mainnet --out-file allpoosID.txt

cardano-cli query stake-pools --mainnet --out-file stakepoolid_bech32.txt

■修正後
以下のコマンドを実行し、赤文字の戻り値があればブロックチェーンに登録されています
ブロックプロデューサーノード

cardano-cli query stake-pools --mainnet --out-file allpoolsID.txt

cat allpoolsID.txt | grep $(cat stakepoolid_bech32.txt)

**Comment by btbf** [comment]
Fixed
