### ISSUE TITLE
[提案]プール運用マニュアル-資金引き出し

### ISSUE THREAD

**Issue by AichiStakePool** [btbf/spojapanguild#90]
提案を１つ書きます。よろしくお願いします。

**問題点
http://49.12.225.142:8000/operation/withdrawal/
において、「Payment.addrからの引き出し」が最初にあるので
報酬からADAを引き出す際に、Payment.addrから引き出してしまう。

**解決策・提案**。
①「Payment.addrからの引き出し」の項目の最初の概要欄にて
「報酬を引き出したい場合は、[2 Stake.addrからの引き出し]を参照してください」
と追記する。

②単純に項目1「Payment.addrからの引き出し」と項目2「Stake.addrからの引き出し」
を入れ替える。

**Comment by btbf** [comment]
Fixed
