### ISSUE TITLE
提案　「ブロック生成可能状態確認」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#91]
提案
構築マニュアルの一番最後、もしくは運用マニュアルの中に、
https://discord.com/channels/747675500297584720/812127470835990558/853983746687238195
こちらのように、完成したプールの設定が正しいかチェックを行う項目があると良いと思いました。

**Comment by btbf** [comment]
チェックプログラム含め現在作成中です。

**Comment by sakakibaraakio** [comment]
了解ですいつもありがとうございます！
