### ISSUE TITLE
修正　運用マニュアル　プール廃止　「コールドキー使用前の権限追加」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#96]
■該当ページURL
https://docs.spojapanguild.net/operation/pool-retire/

■項番(あれば)
1.リタイア処理 

■修正前
登録解除証明書 pool.deregを作成します。
以下のコマンド内の --epoch *** にリタイアしたいエポックを記入します
エアギャップオフラインマシン

cardano-cli stake-pool deregistration-certificate \
--cold-verification-key-file $HOME/cold-keys/node.vkey \
--epoch *** \
--out-file pool.dereg

_______________________________
トランザクションに署名する
エアギャップオフラインマシン

cardano-cli transaction sign \
    --tx-body-file tx.raw \
    --signing-key-file payment.skey \
    --signing-key-file $HOME/cold-keys/node.skey \
    --mainnet \
    --out-file tx.signed

■修正後
登録解除証明書 pool.deregを作成します。
以下のコマンド内の --epoch *** にリタイアしたいエポックを記入します
エアギャップオフラインマシン

chmod u+rwx $HOME/cold-keys
cardano-cli stake-pool deregistration-certificate \
--cold-verification-key-file $HOME/cold-keys/node.vkey \
--epoch *** \
--out-file pool.dereg

_______________________________
トランザクションに署名する
エアギャップオフラインマシン

cardano-cli transaction sign \
    --tx-body-file tx.raw \
    --signing-key-file payment.skey \
    --signing-key-file $HOME/cold-keys/node.skey \
    --mainnet \
    --out-file tx.signed
    
    chmod a-rwx $HOME/cold-keys

**Comment by btbf** [comment]
Fixed
