### ISSUE TITLE
報告　構築マニュアル0 「ダークモードにおけるグラフの視認性」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#97]
■該当ページURL
https://docs.spojapanguild.net/setup/0-start-guide/#_2

■項番(あれば)
0-2.サーバースペック要件
プール構成のイメージ

■報告内容
こちらのページのグラフのみ、ダークモードにおいて一部文字が見えなくなっているようです。
![スクリーンショット 2022-02-27 154353](https://user-images.githubusercontent.com/69729884/155871548-998a2592-2aca-444e-8236-8ebdb824b08a.png)

**Comment by btbf** [comment]
Fixed
