### ISSUE TITLE
報告　「一部の図のレイアウト崩れ」

### ISSUE THREAD

**Issue by sakakibaraakio** [btbf/spojapanguild#98]
■該当ページURL
https://docs.spojapanguild.net/setup/4-bp-setup/#3
https://docs.spojapanguild.net/setup/7-register-stakepool/#2
https://docs.spojapanguild.net/setup/7-register-stakepool/#poolcert
https://docs.spojapanguild.net/setup/7-register-stakepool/#4
https://docs.spojapanguild.net/operation/kes-update/#2kes
https://docs.spojapanguild.net/operation/cert-update/

■項番(あれば)
4-BPセットアップ  3.プール運用証明書の作成
7-ステークプールの登録  2.プール登録証明書の作成
7-ステークプールの登録  2.プール登録証明書の作成 pool.certを作成する 
7-ステークプールの登録  4. プール登録確認
KESの更新 2.新しいKESファイルを生成 
プール情報の更新 

■報告内容
ファイル移動を説明する図において、移動するファイルが2つの時にレイアウトが崩れるようです。
![スクリーンショット 2022-02-27 155750](https://user-images.githubusercontent.com/69729884/155871986-7519a09c-743b-4bfb-8eb6-a9f8243033df.png)

**Comment by btbf** [comment]
FIxed
